// Copyright 2026 icefelix.com. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license
// that can be found in the LICENSE file.
//
// GENERATED CODE — DO NOT EDIT. Edit pigeons/window_api.dart instead.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace icefelix_window_manager {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class WindowHostApi;
  friend class WindowFlutterApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class WindowStateRaw {
  kNormal = 0,
  kMinimized = 1,
  kMaximized = 2,
  kFullscreen = 3,
  kHidden = 4
};

enum class TitleBarStyleRaw {
  kNormal = 0,
  kHidden = 1,
  kHiddenInset = 2
};

enum class ResizeDirectionRaw {
  kTop = 0,
  kBottom = 1,
  kLeft = 2,
  kRight = 3,
  kTopLeft = 4,
  kTopRight = 5,
  kBottomLeft = 6,
  kBottomRight = 7
};

enum class DisplayServerRaw {
  kX11 = 0,
  kWayland = 1
};


// Generated class from Pigeon that represents data sent in messages.
class OffsetRaw {
 public:
  // Constructs an object setting all fields.
  explicit OffsetRaw(
    double dx,
    double dy);

  double dx() const;
  void set_dx(double value_arg);

  double dy() const;
  void set_dy(double value_arg);


 private:
  static OffsetRaw FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class WindowBoundsRaw;
  friend class WindowHostApi;
  friend class WindowFlutterApi;
  friend class PigeonInternalCodecSerializer;
  double dx_;
  double dy_;

};


// Generated class from Pigeon that represents data sent in messages.
class SizeRaw {
 public:
  // Constructs an object setting all fields.
  explicit SizeRaw(
    double width,
    double height);

  double width() const;
  void set_width(double value_arg);

  double height() const;
  void set_height(double value_arg);


 private:
  static SizeRaw FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class WindowBoundsRaw;
  friend class WindowHostApi;
  friend class WindowFlutterApi;
  friend class PigeonInternalCodecSerializer;
  double width_;
  double height_;

};


// Generated class from Pigeon that represents data sent in messages.
class RectRaw {
 public:
  // Constructs an object setting all fields.
  explicit RectRaw(
    double x,
    double y,
    double width,
    double height);

  double x() const;
  void set_x(double value_arg);

  double y() const;
  void set_y(double value_arg);

  double width() const;
  void set_width(double value_arg);

  double height() const;
  void set_height(double value_arg);


 private:
  static RectRaw FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class DisplayRaw;
  friend class WindowHostApi;
  friend class WindowFlutterApi;
  friend class PigeonInternalCodecSerializer;
  double x_;
  double y_;
  double width_;
  double height_;

};


// Generated class from Pigeon that represents data sent in messages.
class WindowBoundsRaw {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit WindowBoundsRaw(const SizeRaw& size);

  // Constructs an object setting all fields.
  explicit WindowBoundsRaw(
    const OffsetRaw* position,
    const SizeRaw& size);

  ~WindowBoundsRaw() = default;
  WindowBoundsRaw(const WindowBoundsRaw& other);
  WindowBoundsRaw& operator=(const WindowBoundsRaw& other);
  WindowBoundsRaw(WindowBoundsRaw&& other) = default;
  WindowBoundsRaw& operator=(WindowBoundsRaw&& other) noexcept = default;
  const OffsetRaw* position() const;
  void set_position(const OffsetRaw* value_arg);
  void set_position(const OffsetRaw& value_arg);

  const SizeRaw& size() const;
  void set_size(const SizeRaw& value_arg);


 private:
  static WindowBoundsRaw FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class WindowSnapshotRaw;
  friend class WindowHostApi;
  friend class WindowFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::unique_ptr<OffsetRaw> position_;
  std::unique_ptr<SizeRaw> size_;

};


// Generated class from Pigeon that represents data sent in messages.
class DisplayRaw {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit DisplayRaw(
    const std::string& id,
    const RectRaw& bounds,
    const RectRaw& work_area,
    double scale_factor,
    bool is_primary);

  // Constructs an object setting all fields.
  explicit DisplayRaw(
    const std::string& id,
    const std::string* name,
    const RectRaw& bounds,
    const RectRaw& work_area,
    const double* physical_width_mm,
    const double* physical_height_mm,
    const double* dpi,
    double scale_factor,
    bool is_primary,
    const int64_t* refresh_rate);

  ~DisplayRaw() = default;
  DisplayRaw(const DisplayRaw& other);
  DisplayRaw& operator=(const DisplayRaw& other);
  DisplayRaw(DisplayRaw&& other) = default;
  DisplayRaw& operator=(DisplayRaw&& other) noexcept = default;
  const std::string& id() const;
  void set_id(std::string_view value_arg);

  const std::string* name() const;
  void set_name(const std::string_view* value_arg);
  void set_name(std::string_view value_arg);

  const RectRaw& bounds() const;
  void set_bounds(const RectRaw& value_arg);

  const RectRaw& work_area() const;
  void set_work_area(const RectRaw& value_arg);

  const double* physical_width_mm() const;
  void set_physical_width_mm(const double* value_arg);
  void set_physical_width_mm(double value_arg);

  const double* physical_height_mm() const;
  void set_physical_height_mm(const double* value_arg);
  void set_physical_height_mm(double value_arg);

  const double* dpi() const;
  void set_dpi(const double* value_arg);
  void set_dpi(double value_arg);

  double scale_factor() const;
  void set_scale_factor(double value_arg);

  bool is_primary() const;
  void set_is_primary(bool value_arg);

  const int64_t* refresh_rate() const;
  void set_refresh_rate(const int64_t* value_arg);
  void set_refresh_rate(int64_t value_arg);


 private:
  static DisplayRaw FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class WindowSnapshotRaw;
  friend class WindowHostApi;
  friend class WindowFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string id_;
  std::optional<std::string> name_;
  std::unique_ptr<RectRaw> bounds_;
  std::unique_ptr<RectRaw> work_area_;
  std::optional<double> physical_width_mm_;
  std::optional<double> physical_height_mm_;
  std::optional<double> dpi_;
  double scale_factor_;
  bool is_primary_;
  std::optional<int64_t> refresh_rate_;

};


// Generated class from Pigeon that represents data sent in messages.
class WindowSnapshotRaw {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit WindowSnapshotRaw(
    const WindowBoundsRaw& bounds,
    const WindowStateRaw& state,
    const std::string& title,
    bool is_focused,
    bool always_on_top,
    bool skip_taskbar,
    bool resizable,
    bool movable,
    bool minimizable,
    bool maximizable,
    bool closable,
    bool frameless,
    const TitleBarStyleRaw& title_bar_style,
    double opacity,
    bool has_shadow,
    bool prevent_close,
    const DisplayRaw& current_display);

  // Constructs an object setting all fields.
  explicit WindowSnapshotRaw(
    const WindowBoundsRaw& bounds,
    const WindowStateRaw& state,
    const std::string& title,
    bool is_focused,
    bool always_on_top,
    bool skip_taskbar,
    bool resizable,
    bool movable,
    bool minimizable,
    bool maximizable,
    bool closable,
    bool frameless,
    const TitleBarStyleRaw& title_bar_style,
    double opacity,
    const int64_t* background_color_argb,
    bool has_shadow,
    bool prevent_close,
    const DisplayRaw& current_display);

  ~WindowSnapshotRaw() = default;
  WindowSnapshotRaw(const WindowSnapshotRaw& other);
  WindowSnapshotRaw& operator=(const WindowSnapshotRaw& other);
  WindowSnapshotRaw(WindowSnapshotRaw&& other) = default;
  WindowSnapshotRaw& operator=(WindowSnapshotRaw&& other) noexcept = default;
  const WindowBoundsRaw& bounds() const;
  void set_bounds(const WindowBoundsRaw& value_arg);

  const WindowStateRaw& state() const;
  void set_state(const WindowStateRaw& value_arg);

  const std::string& title() const;
  void set_title(std::string_view value_arg);

  bool is_focused() const;
  void set_is_focused(bool value_arg);

  bool always_on_top() const;
  void set_always_on_top(bool value_arg);

  bool skip_taskbar() const;
  void set_skip_taskbar(bool value_arg);

  bool resizable() const;
  void set_resizable(bool value_arg);

  bool movable() const;
  void set_movable(bool value_arg);

  bool minimizable() const;
  void set_minimizable(bool value_arg);

  bool maximizable() const;
  void set_maximizable(bool value_arg);

  bool closable() const;
  void set_closable(bool value_arg);

  bool frameless() const;
  void set_frameless(bool value_arg);

  const TitleBarStyleRaw& title_bar_style() const;
  void set_title_bar_style(const TitleBarStyleRaw& value_arg);

  double opacity() const;
  void set_opacity(double value_arg);

  const int64_t* background_color_argb() const;
  void set_background_color_argb(const int64_t* value_arg);
  void set_background_color_argb(int64_t value_arg);

  bool has_shadow() const;
  void set_has_shadow(bool value_arg);

  bool prevent_close() const;
  void set_prevent_close(bool value_arg);

  const DisplayRaw& current_display() const;
  void set_current_display(const DisplayRaw& value_arg);


 private:
  static WindowSnapshotRaw FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class WindowHostApi;
  friend class WindowFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::unique_ptr<WindowBoundsRaw> bounds_;
  WindowStateRaw state_;
  std::string title_;
  bool is_focused_;
  bool always_on_top_;
  bool skip_taskbar_;
  bool resizable_;
  bool movable_;
  bool minimizable_;
  bool maximizable_;
  bool closable_;
  bool frameless_;
  TitleBarStyleRaw title_bar_style_;
  double opacity_;
  std::optional<int64_t> background_color_argb_;
  bool has_shadow_;
  bool prevent_close_;
  std::unique_ptr<DisplayRaw> current_display_;

};


// Generated class from Pigeon that represents data sent in messages.
class PlatformInfoRaw {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit PlatformInfoRaw(
    const std::string& target,
    bool is_sandboxed);

  // Constructs an object setting all fields.
  explicit PlatformInfoRaw(
    const std::string& target,
    const DisplayServerRaw* display_server,
    bool is_sandboxed);

  const std::string& target() const;
  void set_target(std::string_view value_arg);

  const DisplayServerRaw* display_server() const;
  void set_display_server(const DisplayServerRaw* value_arg);
  void set_display_server(const DisplayServerRaw& value_arg);

  bool is_sandboxed() const;
  void set_is_sandboxed(bool value_arg);


 private:
  static PlatformInfoRaw FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class WindowHostApi;
  friend class WindowFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string target_;
  std::optional<DisplayServerRaw> display_server_;
  bool is_sandboxed_;

};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class WindowHostApi {
 public:
  WindowHostApi(const WindowHostApi&) = delete;
  WindowHostApi& operator=(const WindowHostApi&) = delete;
  virtual ~WindowHostApi() {}
  virtual ErrorOr<WindowSnapshotRaw> EnsureInitialized() = 0;
  virtual ErrorOr<PlatformInfoRaw> GetPlatformInfo() = 0;
  virtual ErrorOr<WindowBoundsRaw> GetBounds() = 0;
  // Set window bounds. Coordinate system depends on [displayId]:
  // - If [displayId] is null: bounds.position is in GLOBAL virtual desktop coords.
  // - If [displayId] is provided: bounds.position is RELATIVE to that display's origin.
  //
  // NOTE: distinct from moveToDisplay():
  // - setBounds(bounds, displayId) = "set window to specific bounds, optionally on display X"
  // - moveToDisplay(displayId) = "move window to display X, preserving current relative position"
  // Use setBounds when you have specific coordinates; use moveToDisplay when you just want to switch monitors.
  virtual std::optional<FlutterError> SetBounds(
    const WindowBoundsRaw& bounds,
    const std::string* display_id) = 0;
  // Set the window frame size (titlebar included on platforms that have one).
  // All size APIs and snapshot.bounds.size share this frame-based coordinate
  // space. Top-left position is preserved.
  virtual std::optional<FlutterError> SetSize(const SizeRaw& size) = 0;
  // Set minimum window frame size, or `null` to clear the constraint.
  // Coordinate space matches [setSize] — same frame, including titlebar.
  // Future drag-resize and `setSize` calls clamp against this bound.
  virtual std::optional<FlutterError> SetMinSize(const SizeRaw* size) = 0;
  // Set maximum window frame size, or `null` to clear the constraint.
  // Coordinate space matches [setSize] — same frame, including titlebar.
  // `maximize()` (a.k.a. zoom) also respects this bound.
  virtual std::optional<FlutterError> SetMaxSize(const SizeRaw* size) = 0;
  virtual std::optional<FlutterError> SetPosition(const OffsetRaw& position) = 0;
  virtual std::optional<FlutterError> Center() = 0;
  // Move window to [displayId], **preserving relative position when possible**.
  // If the preserved position doesn't fit on the new display, centers instead.
  // Distinct from setBounds(bounds, displayId) — see setBounds for explicit positioning.
  virtual std::optional<FlutterError> MoveToDisplay(const std::string& display_id) = 0;
  virtual std::optional<FlutterError> Minimize() = 0;
  virtual std::optional<FlutterError> Maximize() = 0;
  virtual std::optional<FlutterError> Unmaximize() = 0;
  virtual std::optional<FlutterError> Restore() = 0;
  virtual std::optional<FlutterError> Hide() = 0;
  virtual std::optional<FlutterError> Show() = 0;
  virtual std::optional<FlutterError> Fullscreen() = 0;
  virtual std::optional<FlutterError> ExitFullscreen() = 0;
  virtual std::optional<FlutterError> Focus() = 0;
  virtual std::optional<FlutterError> Blur() = 0;
  virtual std::optional<FlutterError> StartDrag() = 0;
  virtual std::optional<FlutterError> StartResize(const ResizeDirectionRaw& direction) = 0;
  virtual std::optional<FlutterError> Close() = 0;
  virtual std::optional<FlutterError> Destroy() = 0;
  virtual std::optional<FlutterError> SetTitle(const std::string& title) = 0;
  virtual std::optional<FlutterError> SetAlwaysOnTop(bool value) = 0;
  virtual std::optional<FlutterError> SetSkipTaskbar(bool value) = 0;
  virtual std::optional<FlutterError> SetResizable(bool value) = 0;
  virtual std::optional<FlutterError> SetMovable(bool value) = 0;
  virtual std::optional<FlutterError> SetMinimizable(bool value) = 0;
  virtual std::optional<FlutterError> SetMaximizable(bool value) = 0;
  virtual std::optional<FlutterError> SetClosable(bool value) = 0;
  virtual std::optional<FlutterError> SetFrameless(bool value) = 0;
  virtual std::optional<FlutterError> SetTitleBarStyle(const TitleBarStyleRaw& style) = 0;
  virtual std::optional<FlutterError> SetOpacity(double opacity) = 0;
  virtual std::optional<FlutterError> SetBackgroundColor(int64_t argb) = 0;
  virtual std::optional<FlutterError> SetHasShadow(bool value) = 0;
  virtual std::optional<FlutterError> SetIcon(const std::string& filesystem_path) = 0;
  // Replace the window's visible region with a polygon defined by [points]
  // (window-relative LOGICAL pixels — same coord space as setSize). Pixels
  // outside the polygon are not part of the window at the OS level: they
  // don't paint AND clicks pass through to whatever is behind on the desktop.
  //
  // Pass `null` to clear the shape and restore the default rectangular
  // region.
  //
  // Platform behavior:
  // - Windows: implemented via `CreatePolygonRgn` + `SetWindowRgn`. True
  //   non-rectangular hit-testing. Frameless windows give the cleanest
  //   result (no chrome around the shape).
  // - macOS: best-effort via NSWindow.contentView.layer mask. Hit-testing
  //   for the title bar / chrome is unaffected — clear the title bar via
  //   setFrameless(true) for the desired effect.
  // - Linux: deferred to v0.3.0 (X11 SHAPE extension / Wayland subsurface).
  virtual std::optional<FlutterError> SetShape(const flutter::EncodableList* points) = 0;
  virtual std::optional<FlutterError> SetPreventClose(bool value) = 0;
  virtual ErrorOr<flutter::EncodableList> ListDisplays() = 0;
  virtual ErrorOr<DisplayRaw> GetCurrentDisplay() = 0;
  virtual ErrorOr<DisplayRaw> GetPrimaryDisplay() = 0;

  // The codec used by WindowHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `WindowHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    WindowHostApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    WindowHostApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  WindowHostApi() = default;

};
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class WindowFlutterApi {
 public:
  WindowFlutterApi(flutter::BinaryMessenger* binary_messenger);
  WindowFlutterApi(
    flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const flutter::StandardMessageCodec& GetCodec();
  // Called whenever the window snapshot changes. Single notification for all
  // state transitions — Dart side derives WindowEvent from snapshot diff.
  void OnSnapshotChanged(
    const WindowSnapshotRaw& snapshot,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  // Called when displays are added, removed, or reconfigured.
  void OnDisplaysChanged(
    const flutter::EncodableList& displays,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  // Called when close is requested AND setPreventClose(true) was previously called.
  // Return value: true = allow close (default), false = block.
  //
  // SYNCHRONIZATION CONTRACT FOR NATIVE IMPLEMENTATIONS:
  // - Native side MUST wait for Dart's response before deciding.
  // - Default-allow on timeout: if Dart doesn't respond within 5000ms, treat as `true`
  //   (allow close). Rationale: blocking close indefinitely on a hung Dart isolate
  //   would prevent user from force-quitting the app.
  // - Implementations on macOS/Windows/Linux MUST agree on this timeout to keep
  //   behavior consistent across platforms.
  void OnCloseRequest(
    std::function<void(bool)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);

 private:
  flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace icefelix_window_manager
#endif  // PIGEON_MESSAGES_G_H_
