// Copyright 2026 icefelix.com. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license
// that can be found in the LICENSE file.
//
// GENERATED CODE — DO NOT EDIT. Edit pigeons/window_api.dart instead.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace icefelix_window_manager {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

// OffsetRaw

OffsetRaw::OffsetRaw(
  double dx,
  double dy)
 : dx_(dx),
    dy_(dy) {}

double OffsetRaw::dx() const {
  return dx_;
}

void OffsetRaw::set_dx(double value_arg) {
  dx_ = value_arg;
}


double OffsetRaw::dy() const {
  return dy_;
}

void OffsetRaw::set_dy(double value_arg) {
  dy_ = value_arg;
}


EncodableList OffsetRaw::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(dx_));
  list.push_back(EncodableValue(dy_));
  return list;
}

OffsetRaw OffsetRaw::FromEncodableList(const EncodableList& list) {
  OffsetRaw decoded(
    std::get<double>(list[0]),
    std::get<double>(list[1]));
  return decoded;
}

// SizeRaw

SizeRaw::SizeRaw(
  double width,
  double height)
 : width_(width),
    height_(height) {}

double SizeRaw::width() const {
  return width_;
}

void SizeRaw::set_width(double value_arg) {
  width_ = value_arg;
}


double SizeRaw::height() const {
  return height_;
}

void SizeRaw::set_height(double value_arg) {
  height_ = value_arg;
}


EncodableList SizeRaw::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(width_));
  list.push_back(EncodableValue(height_));
  return list;
}

SizeRaw SizeRaw::FromEncodableList(const EncodableList& list) {
  SizeRaw decoded(
    std::get<double>(list[0]),
    std::get<double>(list[1]));
  return decoded;
}

// RectRaw

RectRaw::RectRaw(
  double x,
  double y,
  double width,
  double height)
 : x_(x),
    y_(y),
    width_(width),
    height_(height) {}

double RectRaw::x() const {
  return x_;
}

void RectRaw::set_x(double value_arg) {
  x_ = value_arg;
}


double RectRaw::y() const {
  return y_;
}

void RectRaw::set_y(double value_arg) {
  y_ = value_arg;
}


double RectRaw::width() const {
  return width_;
}

void RectRaw::set_width(double value_arg) {
  width_ = value_arg;
}


double RectRaw::height() const {
  return height_;
}

void RectRaw::set_height(double value_arg) {
  height_ = value_arg;
}


EncodableList RectRaw::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(EncodableValue(x_));
  list.push_back(EncodableValue(y_));
  list.push_back(EncodableValue(width_));
  list.push_back(EncodableValue(height_));
  return list;
}

RectRaw RectRaw::FromEncodableList(const EncodableList& list) {
  RectRaw decoded(
    std::get<double>(list[0]),
    std::get<double>(list[1]),
    std::get<double>(list[2]),
    std::get<double>(list[3]));
  return decoded;
}

// WindowBoundsRaw

WindowBoundsRaw::WindowBoundsRaw(const SizeRaw& size)
 : size_(std::make_unique<SizeRaw>(size)) {}

WindowBoundsRaw::WindowBoundsRaw(
  const OffsetRaw* position,
  const SizeRaw& size)
 : position_(position ? std::make_unique<OffsetRaw>(*position) : nullptr),
    size_(std::make_unique<SizeRaw>(size)) {}

WindowBoundsRaw::WindowBoundsRaw(const WindowBoundsRaw& other)
 : position_(other.position_ ? std::make_unique<OffsetRaw>(*other.position_) : nullptr),
    size_(std::make_unique<SizeRaw>(*other.size_)) {}

WindowBoundsRaw& WindowBoundsRaw::operator=(const WindowBoundsRaw& other) {
  position_ = other.position_ ? std::make_unique<OffsetRaw>(*other.position_) : nullptr;
  size_ = std::make_unique<SizeRaw>(*other.size_);
  return *this;
}

const OffsetRaw* WindowBoundsRaw::position() const {
  return position_.get();
}

void WindowBoundsRaw::set_position(const OffsetRaw* value_arg) {
  position_ = value_arg ? std::make_unique<OffsetRaw>(*value_arg) : nullptr;
}

void WindowBoundsRaw::set_position(const OffsetRaw& value_arg) {
  position_ = std::make_unique<OffsetRaw>(value_arg);
}


const SizeRaw& WindowBoundsRaw::size() const {
  return *size_;
}

void WindowBoundsRaw::set_size(const SizeRaw& value_arg) {
  size_ = std::make_unique<SizeRaw>(value_arg);
}


EncodableList WindowBoundsRaw::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(position_ ? CustomEncodableValue(*position_) : EncodableValue());
  list.push_back(CustomEncodableValue(*size_));
  return list;
}

WindowBoundsRaw WindowBoundsRaw::FromEncodableList(const EncodableList& list) {
  WindowBoundsRaw decoded(
    std::any_cast<const SizeRaw&>(std::get<CustomEncodableValue>(list[1])));
  auto& encodable_position = list[0];
  if (!encodable_position.IsNull()) {
    decoded.set_position(std::any_cast<const OffsetRaw&>(std::get<CustomEncodableValue>(encodable_position)));
  }
  return decoded;
}

// DisplayRaw

DisplayRaw::DisplayRaw(
  const std::string& id,
  const RectRaw& bounds,
  const RectRaw& work_area,
  double scale_factor,
  bool is_primary)
 : id_(id),
    bounds_(std::make_unique<RectRaw>(bounds)),
    work_area_(std::make_unique<RectRaw>(work_area)),
    scale_factor_(scale_factor),
    is_primary_(is_primary) {}

DisplayRaw::DisplayRaw(
  const std::string& id,
  const std::string* name,
  const RectRaw& bounds,
  const RectRaw& work_area,
  const double* physical_width_mm,
  const double* physical_height_mm,
  const double* dpi,
  double scale_factor,
  bool is_primary,
  const int64_t* refresh_rate)
 : id_(id),
    name_(name ? std::optional<std::string>(*name) : std::nullopt),
    bounds_(std::make_unique<RectRaw>(bounds)),
    work_area_(std::make_unique<RectRaw>(work_area)),
    physical_width_mm_(physical_width_mm ? std::optional<double>(*physical_width_mm) : std::nullopt),
    physical_height_mm_(physical_height_mm ? std::optional<double>(*physical_height_mm) : std::nullopt),
    dpi_(dpi ? std::optional<double>(*dpi) : std::nullopt),
    scale_factor_(scale_factor),
    is_primary_(is_primary),
    refresh_rate_(refresh_rate ? std::optional<int64_t>(*refresh_rate) : std::nullopt) {}

DisplayRaw::DisplayRaw(const DisplayRaw& other)
 : id_(other.id_),
    name_(other.name_ ? std::optional<std::string>(*other.name_) : std::nullopt),
    bounds_(std::make_unique<RectRaw>(*other.bounds_)),
    work_area_(std::make_unique<RectRaw>(*other.work_area_)),
    physical_width_mm_(other.physical_width_mm_ ? std::optional<double>(*other.physical_width_mm_) : std::nullopt),
    physical_height_mm_(other.physical_height_mm_ ? std::optional<double>(*other.physical_height_mm_) : std::nullopt),
    dpi_(other.dpi_ ? std::optional<double>(*other.dpi_) : std::nullopt),
    scale_factor_(other.scale_factor_),
    is_primary_(other.is_primary_),
    refresh_rate_(other.refresh_rate_ ? std::optional<int64_t>(*other.refresh_rate_) : std::nullopt) {}

DisplayRaw& DisplayRaw::operator=(const DisplayRaw& other) {
  id_ = other.id_;
  name_ = other.name_;
  bounds_ = std::make_unique<RectRaw>(*other.bounds_);
  work_area_ = std::make_unique<RectRaw>(*other.work_area_);
  physical_width_mm_ = other.physical_width_mm_;
  physical_height_mm_ = other.physical_height_mm_;
  dpi_ = other.dpi_;
  scale_factor_ = other.scale_factor_;
  is_primary_ = other.is_primary_;
  refresh_rate_ = other.refresh_rate_;
  return *this;
}

const std::string& DisplayRaw::id() const {
  return id_;
}

void DisplayRaw::set_id(std::string_view value_arg) {
  id_ = value_arg;
}


const std::string* DisplayRaw::name() const {
  return name_ ? &(*name_) : nullptr;
}

void DisplayRaw::set_name(const std::string_view* value_arg) {
  name_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void DisplayRaw::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const RectRaw& DisplayRaw::bounds() const {
  return *bounds_;
}

void DisplayRaw::set_bounds(const RectRaw& value_arg) {
  bounds_ = std::make_unique<RectRaw>(value_arg);
}


const RectRaw& DisplayRaw::work_area() const {
  return *work_area_;
}

void DisplayRaw::set_work_area(const RectRaw& value_arg) {
  work_area_ = std::make_unique<RectRaw>(value_arg);
}


const double* DisplayRaw::physical_width_mm() const {
  return physical_width_mm_ ? &(*physical_width_mm_) : nullptr;
}

void DisplayRaw::set_physical_width_mm(const double* value_arg) {
  physical_width_mm_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void DisplayRaw::set_physical_width_mm(double value_arg) {
  physical_width_mm_ = value_arg;
}


const double* DisplayRaw::physical_height_mm() const {
  return physical_height_mm_ ? &(*physical_height_mm_) : nullptr;
}

void DisplayRaw::set_physical_height_mm(const double* value_arg) {
  physical_height_mm_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void DisplayRaw::set_physical_height_mm(double value_arg) {
  physical_height_mm_ = value_arg;
}


const double* DisplayRaw::dpi() const {
  return dpi_ ? &(*dpi_) : nullptr;
}

void DisplayRaw::set_dpi(const double* value_arg) {
  dpi_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void DisplayRaw::set_dpi(double value_arg) {
  dpi_ = value_arg;
}


double DisplayRaw::scale_factor() const {
  return scale_factor_;
}

void DisplayRaw::set_scale_factor(double value_arg) {
  scale_factor_ = value_arg;
}


bool DisplayRaw::is_primary() const {
  return is_primary_;
}

void DisplayRaw::set_is_primary(bool value_arg) {
  is_primary_ = value_arg;
}


const int64_t* DisplayRaw::refresh_rate() const {
  return refresh_rate_ ? &(*refresh_rate_) : nullptr;
}

void DisplayRaw::set_refresh_rate(const int64_t* value_arg) {
  refresh_rate_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void DisplayRaw::set_refresh_rate(int64_t value_arg) {
  refresh_rate_ = value_arg;
}


EncodableList DisplayRaw::ToEncodableList() const {
  EncodableList list;
  list.reserve(10);
  list.push_back(EncodableValue(id_));
  list.push_back(name_ ? EncodableValue(*name_) : EncodableValue());
  list.push_back(CustomEncodableValue(*bounds_));
  list.push_back(CustomEncodableValue(*work_area_));
  list.push_back(physical_width_mm_ ? EncodableValue(*physical_width_mm_) : EncodableValue());
  list.push_back(physical_height_mm_ ? EncodableValue(*physical_height_mm_) : EncodableValue());
  list.push_back(dpi_ ? EncodableValue(*dpi_) : EncodableValue());
  list.push_back(EncodableValue(scale_factor_));
  list.push_back(EncodableValue(is_primary_));
  list.push_back(refresh_rate_ ? EncodableValue(*refresh_rate_) : EncodableValue());
  return list;
}

DisplayRaw DisplayRaw::FromEncodableList(const EncodableList& list) {
  DisplayRaw decoded(
    std::get<std::string>(list[0]),
    std::any_cast<const RectRaw&>(std::get<CustomEncodableValue>(list[2])),
    std::any_cast<const RectRaw&>(std::get<CustomEncodableValue>(list[3])),
    std::get<double>(list[7]),
    std::get<bool>(list[8]));
  auto& encodable_name = list[1];
  if (!encodable_name.IsNull()) {
    decoded.set_name(std::get<std::string>(encodable_name));
  }
  auto& encodable_physical_width_mm = list[4];
  if (!encodable_physical_width_mm.IsNull()) {
    decoded.set_physical_width_mm(std::get<double>(encodable_physical_width_mm));
  }
  auto& encodable_physical_height_mm = list[5];
  if (!encodable_physical_height_mm.IsNull()) {
    decoded.set_physical_height_mm(std::get<double>(encodable_physical_height_mm));
  }
  auto& encodable_dpi = list[6];
  if (!encodable_dpi.IsNull()) {
    decoded.set_dpi(std::get<double>(encodable_dpi));
  }
  auto& encodable_refresh_rate = list[9];
  if (!encodable_refresh_rate.IsNull()) {
    decoded.set_refresh_rate(std::get<int64_t>(encodable_refresh_rate));
  }
  return decoded;
}

// WindowSnapshotRaw

WindowSnapshotRaw::WindowSnapshotRaw(
  const WindowBoundsRaw& bounds,
  const WindowStateRaw& state,
  const std::string& title,
  bool is_focused,
  bool always_on_top,
  bool skip_taskbar,
  bool resizable,
  bool movable,
  bool minimizable,
  bool maximizable,
  bool closable,
  bool frameless,
  const TitleBarStyleRaw& title_bar_style,
  double opacity,
  bool has_shadow,
  bool prevent_close,
  const DisplayRaw& current_display)
 : bounds_(std::make_unique<WindowBoundsRaw>(bounds)),
    state_(state),
    title_(title),
    is_focused_(is_focused),
    always_on_top_(always_on_top),
    skip_taskbar_(skip_taskbar),
    resizable_(resizable),
    movable_(movable),
    minimizable_(minimizable),
    maximizable_(maximizable),
    closable_(closable),
    frameless_(frameless),
    title_bar_style_(title_bar_style),
    opacity_(opacity),
    has_shadow_(has_shadow),
    prevent_close_(prevent_close),
    current_display_(std::make_unique<DisplayRaw>(current_display)) {}

WindowSnapshotRaw::WindowSnapshotRaw(
  const WindowBoundsRaw& bounds,
  const WindowStateRaw& state,
  const std::string& title,
  bool is_focused,
  bool always_on_top,
  bool skip_taskbar,
  bool resizable,
  bool movable,
  bool minimizable,
  bool maximizable,
  bool closable,
  bool frameless,
  const TitleBarStyleRaw& title_bar_style,
  double opacity,
  const int64_t* background_color_argb,
  bool has_shadow,
  bool prevent_close,
  const DisplayRaw& current_display)
 : bounds_(std::make_unique<WindowBoundsRaw>(bounds)),
    state_(state),
    title_(title),
    is_focused_(is_focused),
    always_on_top_(always_on_top),
    skip_taskbar_(skip_taskbar),
    resizable_(resizable),
    movable_(movable),
    minimizable_(minimizable),
    maximizable_(maximizable),
    closable_(closable),
    frameless_(frameless),
    title_bar_style_(title_bar_style),
    opacity_(opacity),
    background_color_argb_(background_color_argb ? std::optional<int64_t>(*background_color_argb) : std::nullopt),
    has_shadow_(has_shadow),
    prevent_close_(prevent_close),
    current_display_(std::make_unique<DisplayRaw>(current_display)) {}

WindowSnapshotRaw::WindowSnapshotRaw(const WindowSnapshotRaw& other)
 : bounds_(std::make_unique<WindowBoundsRaw>(*other.bounds_)),
    state_(other.state_),
    title_(other.title_),
    is_focused_(other.is_focused_),
    always_on_top_(other.always_on_top_),
    skip_taskbar_(other.skip_taskbar_),
    resizable_(other.resizable_),
    movable_(other.movable_),
    minimizable_(other.minimizable_),
    maximizable_(other.maximizable_),
    closable_(other.closable_),
    frameless_(other.frameless_),
    title_bar_style_(other.title_bar_style_),
    opacity_(other.opacity_),
    background_color_argb_(other.background_color_argb_ ? std::optional<int64_t>(*other.background_color_argb_) : std::nullopt),
    has_shadow_(other.has_shadow_),
    prevent_close_(other.prevent_close_),
    current_display_(std::make_unique<DisplayRaw>(*other.current_display_)) {}

WindowSnapshotRaw& WindowSnapshotRaw::operator=(const WindowSnapshotRaw& other) {
  bounds_ = std::make_unique<WindowBoundsRaw>(*other.bounds_);
  state_ = other.state_;
  title_ = other.title_;
  is_focused_ = other.is_focused_;
  always_on_top_ = other.always_on_top_;
  skip_taskbar_ = other.skip_taskbar_;
  resizable_ = other.resizable_;
  movable_ = other.movable_;
  minimizable_ = other.minimizable_;
  maximizable_ = other.maximizable_;
  closable_ = other.closable_;
  frameless_ = other.frameless_;
  title_bar_style_ = other.title_bar_style_;
  opacity_ = other.opacity_;
  background_color_argb_ = other.background_color_argb_;
  has_shadow_ = other.has_shadow_;
  prevent_close_ = other.prevent_close_;
  current_display_ = std::make_unique<DisplayRaw>(*other.current_display_);
  return *this;
}

const WindowBoundsRaw& WindowSnapshotRaw::bounds() const {
  return *bounds_;
}

void WindowSnapshotRaw::set_bounds(const WindowBoundsRaw& value_arg) {
  bounds_ = std::make_unique<WindowBoundsRaw>(value_arg);
}


const WindowStateRaw& WindowSnapshotRaw::state() const {
  return state_;
}

void WindowSnapshotRaw::set_state(const WindowStateRaw& value_arg) {
  state_ = value_arg;
}


const std::string& WindowSnapshotRaw::title() const {
  return title_;
}

void WindowSnapshotRaw::set_title(std::string_view value_arg) {
  title_ = value_arg;
}


bool WindowSnapshotRaw::is_focused() const {
  return is_focused_;
}

void WindowSnapshotRaw::set_is_focused(bool value_arg) {
  is_focused_ = value_arg;
}


bool WindowSnapshotRaw::always_on_top() const {
  return always_on_top_;
}

void WindowSnapshotRaw::set_always_on_top(bool value_arg) {
  always_on_top_ = value_arg;
}


bool WindowSnapshotRaw::skip_taskbar() const {
  return skip_taskbar_;
}

void WindowSnapshotRaw::set_skip_taskbar(bool value_arg) {
  skip_taskbar_ = value_arg;
}


bool WindowSnapshotRaw::resizable() const {
  return resizable_;
}

void WindowSnapshotRaw::set_resizable(bool value_arg) {
  resizable_ = value_arg;
}


bool WindowSnapshotRaw::movable() const {
  return movable_;
}

void WindowSnapshotRaw::set_movable(bool value_arg) {
  movable_ = value_arg;
}


bool WindowSnapshotRaw::minimizable() const {
  return minimizable_;
}

void WindowSnapshotRaw::set_minimizable(bool value_arg) {
  minimizable_ = value_arg;
}


bool WindowSnapshotRaw::maximizable() const {
  return maximizable_;
}

void WindowSnapshotRaw::set_maximizable(bool value_arg) {
  maximizable_ = value_arg;
}


bool WindowSnapshotRaw::closable() const {
  return closable_;
}

void WindowSnapshotRaw::set_closable(bool value_arg) {
  closable_ = value_arg;
}


bool WindowSnapshotRaw::frameless() const {
  return frameless_;
}

void WindowSnapshotRaw::set_frameless(bool value_arg) {
  frameless_ = value_arg;
}


const TitleBarStyleRaw& WindowSnapshotRaw::title_bar_style() const {
  return title_bar_style_;
}

void WindowSnapshotRaw::set_title_bar_style(const TitleBarStyleRaw& value_arg) {
  title_bar_style_ = value_arg;
}


double WindowSnapshotRaw::opacity() const {
  return opacity_;
}

void WindowSnapshotRaw::set_opacity(double value_arg) {
  opacity_ = value_arg;
}


const int64_t* WindowSnapshotRaw::background_color_argb() const {
  return background_color_argb_ ? &(*background_color_argb_) : nullptr;
}

void WindowSnapshotRaw::set_background_color_argb(const int64_t* value_arg) {
  background_color_argb_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void WindowSnapshotRaw::set_background_color_argb(int64_t value_arg) {
  background_color_argb_ = value_arg;
}


bool WindowSnapshotRaw::has_shadow() const {
  return has_shadow_;
}

void WindowSnapshotRaw::set_has_shadow(bool value_arg) {
  has_shadow_ = value_arg;
}


bool WindowSnapshotRaw::prevent_close() const {
  return prevent_close_;
}

void WindowSnapshotRaw::set_prevent_close(bool value_arg) {
  prevent_close_ = value_arg;
}


const DisplayRaw& WindowSnapshotRaw::current_display() const {
  return *current_display_;
}

void WindowSnapshotRaw::set_current_display(const DisplayRaw& value_arg) {
  current_display_ = std::make_unique<DisplayRaw>(value_arg);
}


EncodableList WindowSnapshotRaw::ToEncodableList() const {
  EncodableList list;
  list.reserve(18);
  list.push_back(CustomEncodableValue(*bounds_));
  list.push_back(CustomEncodableValue(state_));
  list.push_back(EncodableValue(title_));
  list.push_back(EncodableValue(is_focused_));
  list.push_back(EncodableValue(always_on_top_));
  list.push_back(EncodableValue(skip_taskbar_));
  list.push_back(EncodableValue(resizable_));
  list.push_back(EncodableValue(movable_));
  list.push_back(EncodableValue(minimizable_));
  list.push_back(EncodableValue(maximizable_));
  list.push_back(EncodableValue(closable_));
  list.push_back(EncodableValue(frameless_));
  list.push_back(CustomEncodableValue(title_bar_style_));
  list.push_back(EncodableValue(opacity_));
  list.push_back(background_color_argb_ ? EncodableValue(*background_color_argb_) : EncodableValue());
  list.push_back(EncodableValue(has_shadow_));
  list.push_back(EncodableValue(prevent_close_));
  list.push_back(CustomEncodableValue(*current_display_));
  return list;
}

WindowSnapshotRaw WindowSnapshotRaw::FromEncodableList(const EncodableList& list) {
  WindowSnapshotRaw decoded(
    std::any_cast<const WindowBoundsRaw&>(std::get<CustomEncodableValue>(list[0])),
    std::any_cast<const WindowStateRaw&>(std::get<CustomEncodableValue>(list[1])),
    std::get<std::string>(list[2]),
    std::get<bool>(list[3]),
    std::get<bool>(list[4]),
    std::get<bool>(list[5]),
    std::get<bool>(list[6]),
    std::get<bool>(list[7]),
    std::get<bool>(list[8]),
    std::get<bool>(list[9]),
    std::get<bool>(list[10]),
    std::get<bool>(list[11]),
    std::any_cast<const TitleBarStyleRaw&>(std::get<CustomEncodableValue>(list[12])),
    std::get<double>(list[13]),
    std::get<bool>(list[15]),
    std::get<bool>(list[16]),
    std::any_cast<const DisplayRaw&>(std::get<CustomEncodableValue>(list[17])));
  auto& encodable_background_color_argb = list[14];
  if (!encodable_background_color_argb.IsNull()) {
    decoded.set_background_color_argb(std::get<int64_t>(encodable_background_color_argb));
  }
  return decoded;
}

// PlatformInfoRaw

PlatformInfoRaw::PlatformInfoRaw(
  const std::string& target,
  bool is_sandboxed)
 : target_(target),
    is_sandboxed_(is_sandboxed) {}

PlatformInfoRaw::PlatformInfoRaw(
  const std::string& target,
  const DisplayServerRaw* display_server,
  bool is_sandboxed)
 : target_(target),
    display_server_(display_server ? std::optional<DisplayServerRaw>(*display_server) : std::nullopt),
    is_sandboxed_(is_sandboxed) {}

const std::string& PlatformInfoRaw::target() const {
  return target_;
}

void PlatformInfoRaw::set_target(std::string_view value_arg) {
  target_ = value_arg;
}


const DisplayServerRaw* PlatformInfoRaw::display_server() const {
  return display_server_ ? &(*display_server_) : nullptr;
}

void PlatformInfoRaw::set_display_server(const DisplayServerRaw* value_arg) {
  display_server_ = value_arg ? std::optional<DisplayServerRaw>(*value_arg) : std::nullopt;
}

void PlatformInfoRaw::set_display_server(const DisplayServerRaw& value_arg) {
  display_server_ = value_arg;
}


bool PlatformInfoRaw::is_sandboxed() const {
  return is_sandboxed_;
}

void PlatformInfoRaw::set_is_sandboxed(bool value_arg) {
  is_sandboxed_ = value_arg;
}


EncodableList PlatformInfoRaw::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(target_));
  list.push_back(display_server_ ? CustomEncodableValue(*display_server_) : EncodableValue());
  list.push_back(EncodableValue(is_sandboxed_));
  return list;
}

PlatformInfoRaw PlatformInfoRaw::FromEncodableList(const EncodableList& list) {
  PlatformInfoRaw decoded(
    std::get<std::string>(list[0]),
    std::get<bool>(list[2]));
  auto& encodable_display_server = list[1];
  if (!encodable_display_server.IsNull()) {
    decoded.set_display_server(std::any_cast<const DisplayServerRaw&>(std::get<CustomEncodableValue>(encodable_display_server)));
  }
  return decoded;
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<WindowStateRaw>(enum_arg_value));
      }
    case 130: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<TitleBarStyleRaw>(enum_arg_value));
      }
    case 131: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<ResizeDirectionRaw>(enum_arg_value));
      }
    case 132: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<DisplayServerRaw>(enum_arg_value));
      }
    case 133: {
        return CustomEncodableValue(OffsetRaw::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 134: {
        return CustomEncodableValue(SizeRaw::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 135: {
        return CustomEncodableValue(RectRaw::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 136: {
        return CustomEncodableValue(WindowBoundsRaw::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 137: {
        return CustomEncodableValue(DisplayRaw::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 138: {
        return CustomEncodableValue(WindowSnapshotRaw::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 139: {
        return CustomEncodableValue(PlatformInfoRaw::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(WindowStateRaw)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<WindowStateRaw>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(TitleBarStyleRaw)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<TitleBarStyleRaw>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(ResizeDirectionRaw)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<ResizeDirectionRaw>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(DisplayServerRaw)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<DisplayServerRaw>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(OffsetRaw)) {
      stream->WriteByte(133);
      WriteValue(EncodableValue(std::any_cast<OffsetRaw>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(SizeRaw)) {
      stream->WriteByte(134);
      WriteValue(EncodableValue(std::any_cast<SizeRaw>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(RectRaw)) {
      stream->WriteByte(135);
      WriteValue(EncodableValue(std::any_cast<RectRaw>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(WindowBoundsRaw)) {
      stream->WriteByte(136);
      WriteValue(EncodableValue(std::any_cast<WindowBoundsRaw>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(DisplayRaw)) {
      stream->WriteByte(137);
      WriteValue(EncodableValue(std::any_cast<DisplayRaw>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(WindowSnapshotRaw)) {
      stream->WriteByte(138);
      WriteValue(EncodableValue(std::any_cast<WindowSnapshotRaw>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformInfoRaw)) {
      stream->WriteByte(139);
      WriteValue(EncodableValue(std::any_cast<PlatformInfoRaw>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by WindowHostApi.
const flutter::StandardMessageCodec& WindowHostApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `WindowHostApi` to handle messages through the `binary_messenger`.
void WindowHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  WindowHostApi* api) {
  WindowHostApi::SetUp(binary_messenger, api, "");
}

void WindowHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  WindowHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.ensureInitialized" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<WindowSnapshotRaw> output = api->EnsureInitialized();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.getPlatformInfo" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<PlatformInfoRaw> output = api->GetPlatformInfo();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.getBounds" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<WindowBoundsRaw> output = api->GetBounds();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.setBounds" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_bounds_arg = args.at(0);
          if (encodable_bounds_arg.IsNull()) {
            reply(WrapError("bounds_arg unexpectedly null."));
            return;
          }
          const auto& bounds_arg = std::any_cast<const WindowBoundsRaw&>(std::get<CustomEncodableValue>(encodable_bounds_arg));
          const auto& encodable_display_id_arg = args.at(1);
          const auto* display_id_arg = std::get_if<std::string>(&encodable_display_id_arg);
          std::optional<FlutterError> output = api->SetBounds(bounds_arg, display_id_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.setSize" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_size_arg = args.at(0);
          if (encodable_size_arg.IsNull()) {
            reply(WrapError("size_arg unexpectedly null."));
            return;
          }
          const auto& size_arg = std::any_cast<const SizeRaw&>(std::get<CustomEncodableValue>(encodable_size_arg));
          std::optional<FlutterError> output = api->SetSize(size_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.setMinSize" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_size_arg = args.at(0);
          const auto* size_arg = encodable_size_arg.IsNull() ? nullptr : &(std::any_cast<const SizeRaw&>(std::get<CustomEncodableValue>(encodable_size_arg)));
          std::optional<FlutterError> output = api->SetMinSize(size_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.setMaxSize" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_size_arg = args.at(0);
          const auto* size_arg = encodable_size_arg.IsNull() ? nullptr : &(std::any_cast<const SizeRaw&>(std::get<CustomEncodableValue>(encodable_size_arg)));
          std::optional<FlutterError> output = api->SetMaxSize(size_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.setPosition" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_position_arg = args.at(0);
          if (encodable_position_arg.IsNull()) {
            reply(WrapError("position_arg unexpectedly null."));
            return;
          }
          const auto& position_arg = std::any_cast<const OffsetRaw&>(std::get<CustomEncodableValue>(encodable_position_arg));
          std::optional<FlutterError> output = api->SetPosition(position_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.center" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->Center();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.moveToDisplay" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_display_id_arg = args.at(0);
          if (encodable_display_id_arg.IsNull()) {
            reply(WrapError("display_id_arg unexpectedly null."));
            return;
          }
          const auto& display_id_arg = std::get<std::string>(encodable_display_id_arg);
          std::optional<FlutterError> output = api->MoveToDisplay(display_id_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.minimize" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->Minimize();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.maximize" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->Maximize();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.unmaximize" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->Unmaximize();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.restore" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->Restore();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.hide" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->Hide();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.show" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->Show();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.fullscreen" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->Fullscreen();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.exitFullscreen" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->ExitFullscreen();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.focus" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->Focus();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.blur" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->Blur();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.startDrag" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->StartDrag();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.startResize" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_direction_arg = args.at(0);
          if (encodable_direction_arg.IsNull()) {
            reply(WrapError("direction_arg unexpectedly null."));
            return;
          }
          const auto& direction_arg = std::any_cast<const ResizeDirectionRaw&>(std::get<CustomEncodableValue>(encodable_direction_arg));
          std::optional<FlutterError> output = api->StartResize(direction_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.close" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->Close();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.destroy" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->Destroy();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.setTitle" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_title_arg = args.at(0);
          if (encodable_title_arg.IsNull()) {
            reply(WrapError("title_arg unexpectedly null."));
            return;
          }
          const auto& title_arg = std::get<std::string>(encodable_title_arg);
          std::optional<FlutterError> output = api->SetTitle(title_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.setAlwaysOnTop" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_value_arg = args.at(0);
          if (encodable_value_arg.IsNull()) {
            reply(WrapError("value_arg unexpectedly null."));
            return;
          }
          const auto& value_arg = std::get<bool>(encodable_value_arg);
          std::optional<FlutterError> output = api->SetAlwaysOnTop(value_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.setSkipTaskbar" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_value_arg = args.at(0);
          if (encodable_value_arg.IsNull()) {
            reply(WrapError("value_arg unexpectedly null."));
            return;
          }
          const auto& value_arg = std::get<bool>(encodable_value_arg);
          std::optional<FlutterError> output = api->SetSkipTaskbar(value_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.setResizable" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_value_arg = args.at(0);
          if (encodable_value_arg.IsNull()) {
            reply(WrapError("value_arg unexpectedly null."));
            return;
          }
          const auto& value_arg = std::get<bool>(encodable_value_arg);
          std::optional<FlutterError> output = api->SetResizable(value_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.setMovable" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_value_arg = args.at(0);
          if (encodable_value_arg.IsNull()) {
            reply(WrapError("value_arg unexpectedly null."));
            return;
          }
          const auto& value_arg = std::get<bool>(encodable_value_arg);
          std::optional<FlutterError> output = api->SetMovable(value_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.setMinimizable" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_value_arg = args.at(0);
          if (encodable_value_arg.IsNull()) {
            reply(WrapError("value_arg unexpectedly null."));
            return;
          }
          const auto& value_arg = std::get<bool>(encodable_value_arg);
          std::optional<FlutterError> output = api->SetMinimizable(value_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.setMaximizable" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_value_arg = args.at(0);
          if (encodable_value_arg.IsNull()) {
            reply(WrapError("value_arg unexpectedly null."));
            return;
          }
          const auto& value_arg = std::get<bool>(encodable_value_arg);
          std::optional<FlutterError> output = api->SetMaximizable(value_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.setClosable" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_value_arg = args.at(0);
          if (encodable_value_arg.IsNull()) {
            reply(WrapError("value_arg unexpectedly null."));
            return;
          }
          const auto& value_arg = std::get<bool>(encodable_value_arg);
          std::optional<FlutterError> output = api->SetClosable(value_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.setFrameless" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_value_arg = args.at(0);
          if (encodable_value_arg.IsNull()) {
            reply(WrapError("value_arg unexpectedly null."));
            return;
          }
          const auto& value_arg = std::get<bool>(encodable_value_arg);
          std::optional<FlutterError> output = api->SetFrameless(value_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.setTitleBarStyle" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_style_arg = args.at(0);
          if (encodable_style_arg.IsNull()) {
            reply(WrapError("style_arg unexpectedly null."));
            return;
          }
          const auto& style_arg = std::any_cast<const TitleBarStyleRaw&>(std::get<CustomEncodableValue>(encodable_style_arg));
          std::optional<FlutterError> output = api->SetTitleBarStyle(style_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.setOpacity" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_opacity_arg = args.at(0);
          if (encodable_opacity_arg.IsNull()) {
            reply(WrapError("opacity_arg unexpectedly null."));
            return;
          }
          const auto& opacity_arg = std::get<double>(encodable_opacity_arg);
          std::optional<FlutterError> output = api->SetOpacity(opacity_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.setBackgroundColor" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_argb_arg = args.at(0);
          if (encodable_argb_arg.IsNull()) {
            reply(WrapError("argb_arg unexpectedly null."));
            return;
          }
          const int64_t argb_arg = encodable_argb_arg.LongValue();
          std::optional<FlutterError> output = api->SetBackgroundColor(argb_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.setHasShadow" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_value_arg = args.at(0);
          if (encodable_value_arg.IsNull()) {
            reply(WrapError("value_arg unexpectedly null."));
            return;
          }
          const auto& value_arg = std::get<bool>(encodable_value_arg);
          std::optional<FlutterError> output = api->SetHasShadow(value_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.setIcon" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_filesystem_path_arg = args.at(0);
          if (encodable_filesystem_path_arg.IsNull()) {
            reply(WrapError("filesystem_path_arg unexpectedly null."));
            return;
          }
          const auto& filesystem_path_arg = std::get<std::string>(encodable_filesystem_path_arg);
          std::optional<FlutterError> output = api->SetIcon(filesystem_path_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.setShape" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_points_arg = args.at(0);
          const auto* points_arg = std::get_if<EncodableList>(&encodable_points_arg);
          std::optional<FlutterError> output = api->SetShape(points_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.setPreventClose" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_value_arg = args.at(0);
          if (encodable_value_arg.IsNull()) {
            reply(WrapError("value_arg unexpectedly null."));
            return;
          }
          const auto& value_arg = std::get<bool>(encodable_value_arg);
          std::optional<FlutterError> output = api->SetPreventClose(value_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.listDisplays" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<EncodableList> output = api->ListDisplays();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.getCurrentDisplay" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<DisplayRaw> output = api->GetCurrentDisplay();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.icefelix_window_manager.WindowHostApi.getPrimaryDisplay" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<DisplayRaw> output = api->GetPrimaryDisplay();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue WindowHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue WindowHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
WindowFlutterApi::WindowFlutterApi(flutter::BinaryMessenger* binary_messenger)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_("") {}

WindowFlutterApi::WindowFlutterApi(
  flutter::BinaryMessenger* binary_messenger,
  const std::string& message_channel_suffix)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_(message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "") {}

const flutter::StandardMessageCodec& WindowFlutterApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

void WindowFlutterApi::OnSnapshotChanged(
  const WindowSnapshotRaw& snapshot_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.icefelix_window_manager.WindowFlutterApi.onSnapshotChanged" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(snapshot_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void WindowFlutterApi::OnDisplaysChanged(
  const EncodableList& displays_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.icefelix_window_manager.WindowFlutterApi.onDisplaysChanged" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(displays_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void WindowFlutterApi::OnCloseRequest(
  std::function<void(bool)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.icefelix_window_manager.WindowFlutterApi.onCloseRequest" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue();
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        const auto& return_value = std::get<bool>(list_return_value->at(0));
        on_success(return_value);
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

}  // namespace icefelix_window_manager
