// Copyright 2026 icefelix.com. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license
// that can be found in the LICENSE file.
//
// GENERATED CODE — DO NOT EDIT. Edit pigeons/window_api.dart instead.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * IcefelixWindowManagerWindowStateRaw:
 * ICEFELIX_WINDOW_MANAGER_WINDOW_STATE_RAW_NORMAL:
 * ICEFELIX_WINDOW_MANAGER_WINDOW_STATE_RAW_MINIMIZED:
 * ICEFELIX_WINDOW_MANAGER_WINDOW_STATE_RAW_MAXIMIZED:
 * ICEFELIX_WINDOW_MANAGER_WINDOW_STATE_RAW_FULLSCREEN:
 * ICEFELIX_WINDOW_MANAGER_WINDOW_STATE_RAW_HIDDEN:
 *
 */
typedef enum {
  ICEFELIX_WINDOW_MANAGER_WINDOW_STATE_RAW_NORMAL = 0,
  ICEFELIX_WINDOW_MANAGER_WINDOW_STATE_RAW_MINIMIZED = 1,
  ICEFELIX_WINDOW_MANAGER_WINDOW_STATE_RAW_MAXIMIZED = 2,
  ICEFELIX_WINDOW_MANAGER_WINDOW_STATE_RAW_FULLSCREEN = 3,
  ICEFELIX_WINDOW_MANAGER_WINDOW_STATE_RAW_HIDDEN = 4
} IcefelixWindowManagerWindowStateRaw;

/**
 * IcefelixWindowManagerTitleBarStyleRaw:
 * ICEFELIX_WINDOW_MANAGER_TITLE_BAR_STYLE_RAW_NORMAL:
 * ICEFELIX_WINDOW_MANAGER_TITLE_BAR_STYLE_RAW_HIDDEN:
 * ICEFELIX_WINDOW_MANAGER_TITLE_BAR_STYLE_RAW_HIDDEN_INSET:
 *
 */
typedef enum {
  ICEFELIX_WINDOW_MANAGER_TITLE_BAR_STYLE_RAW_NORMAL = 0,
  ICEFELIX_WINDOW_MANAGER_TITLE_BAR_STYLE_RAW_HIDDEN = 1,
  ICEFELIX_WINDOW_MANAGER_TITLE_BAR_STYLE_RAW_HIDDEN_INSET = 2
} IcefelixWindowManagerTitleBarStyleRaw;

/**
 * IcefelixWindowManagerResizeDirectionRaw:
 * ICEFELIX_WINDOW_MANAGER_RESIZE_DIRECTION_RAW_TOP:
 * ICEFELIX_WINDOW_MANAGER_RESIZE_DIRECTION_RAW_BOTTOM:
 * ICEFELIX_WINDOW_MANAGER_RESIZE_DIRECTION_RAW_LEFT:
 * ICEFELIX_WINDOW_MANAGER_RESIZE_DIRECTION_RAW_RIGHT:
 * ICEFELIX_WINDOW_MANAGER_RESIZE_DIRECTION_RAW_TOP_LEFT:
 * ICEFELIX_WINDOW_MANAGER_RESIZE_DIRECTION_RAW_TOP_RIGHT:
 * ICEFELIX_WINDOW_MANAGER_RESIZE_DIRECTION_RAW_BOTTOM_LEFT:
 * ICEFELIX_WINDOW_MANAGER_RESIZE_DIRECTION_RAW_BOTTOM_RIGHT:
 *
 */
typedef enum {
  ICEFELIX_WINDOW_MANAGER_RESIZE_DIRECTION_RAW_TOP = 0,
  ICEFELIX_WINDOW_MANAGER_RESIZE_DIRECTION_RAW_BOTTOM = 1,
  ICEFELIX_WINDOW_MANAGER_RESIZE_DIRECTION_RAW_LEFT = 2,
  ICEFELIX_WINDOW_MANAGER_RESIZE_DIRECTION_RAW_RIGHT = 3,
  ICEFELIX_WINDOW_MANAGER_RESIZE_DIRECTION_RAW_TOP_LEFT = 4,
  ICEFELIX_WINDOW_MANAGER_RESIZE_DIRECTION_RAW_TOP_RIGHT = 5,
  ICEFELIX_WINDOW_MANAGER_RESIZE_DIRECTION_RAW_BOTTOM_LEFT = 6,
  ICEFELIX_WINDOW_MANAGER_RESIZE_DIRECTION_RAW_BOTTOM_RIGHT = 7
} IcefelixWindowManagerResizeDirectionRaw;

/**
 * IcefelixWindowManagerDisplayServerRaw:
 * ICEFELIX_WINDOW_MANAGER_DISPLAY_SERVER_RAW_X11:
 * ICEFELIX_WINDOW_MANAGER_DISPLAY_SERVER_RAW_WAYLAND:
 *
 */
typedef enum {
  ICEFELIX_WINDOW_MANAGER_DISPLAY_SERVER_RAW_X11 = 0,
  ICEFELIX_WINDOW_MANAGER_DISPLAY_SERVER_RAW_WAYLAND = 1
} IcefelixWindowManagerDisplayServerRaw;

/**
 * IcefelixWindowManagerOffsetRaw:
 *
 */

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerOffsetRaw, icefelix_window_manager_offset_raw, ICEFELIX_WINDOW_MANAGER, OFFSET_RAW, GObject)

/**
 * icefelix_window_manager_offset_raw_new:
 * dx: field in this object.
 * dy: field in this object.
 *
 * Creates a new #OffsetRaw object.
 *
 * Returns: a new #IcefelixWindowManagerOffsetRaw
 */
IcefelixWindowManagerOffsetRaw* icefelix_window_manager_offset_raw_new(double dx, double dy);

/**
 * icefelix_window_manager_offset_raw_get_dx
 * @object: a #IcefelixWindowManagerOffsetRaw.
 *
 * Gets the value of the dx field of @object.
 *
 * Returns: the field value.
 */
double icefelix_window_manager_offset_raw_get_dx(IcefelixWindowManagerOffsetRaw* object);

/**
 * icefelix_window_manager_offset_raw_get_dy
 * @object: a #IcefelixWindowManagerOffsetRaw.
 *
 * Gets the value of the dy field of @object.
 *
 * Returns: the field value.
 */
double icefelix_window_manager_offset_raw_get_dy(IcefelixWindowManagerOffsetRaw* object);

/**
 * IcefelixWindowManagerSizeRaw:
 *
 */

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerSizeRaw, icefelix_window_manager_size_raw, ICEFELIX_WINDOW_MANAGER, SIZE_RAW, GObject)

/**
 * icefelix_window_manager_size_raw_new:
 * width: field in this object.
 * height: field in this object.
 *
 * Creates a new #SizeRaw object.
 *
 * Returns: a new #IcefelixWindowManagerSizeRaw
 */
IcefelixWindowManagerSizeRaw* icefelix_window_manager_size_raw_new(double width, double height);

/**
 * icefelix_window_manager_size_raw_get_width
 * @object: a #IcefelixWindowManagerSizeRaw.
 *
 * Gets the value of the width field of @object.
 *
 * Returns: the field value.
 */
double icefelix_window_manager_size_raw_get_width(IcefelixWindowManagerSizeRaw* object);

/**
 * icefelix_window_manager_size_raw_get_height
 * @object: a #IcefelixWindowManagerSizeRaw.
 *
 * Gets the value of the height field of @object.
 *
 * Returns: the field value.
 */
double icefelix_window_manager_size_raw_get_height(IcefelixWindowManagerSizeRaw* object);

/**
 * IcefelixWindowManagerRectRaw:
 *
 */

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerRectRaw, icefelix_window_manager_rect_raw, ICEFELIX_WINDOW_MANAGER, RECT_RAW, GObject)

/**
 * icefelix_window_manager_rect_raw_new:
 * x: field in this object.
 * y: field in this object.
 * width: field in this object.
 * height: field in this object.
 *
 * Creates a new #RectRaw object.
 *
 * Returns: a new #IcefelixWindowManagerRectRaw
 */
IcefelixWindowManagerRectRaw* icefelix_window_manager_rect_raw_new(double x, double y, double width, double height);

/**
 * icefelix_window_manager_rect_raw_get_x
 * @object: a #IcefelixWindowManagerRectRaw.
 *
 * Gets the value of the x field of @object.
 *
 * Returns: the field value.
 */
double icefelix_window_manager_rect_raw_get_x(IcefelixWindowManagerRectRaw* object);

/**
 * icefelix_window_manager_rect_raw_get_y
 * @object: a #IcefelixWindowManagerRectRaw.
 *
 * Gets the value of the y field of @object.
 *
 * Returns: the field value.
 */
double icefelix_window_manager_rect_raw_get_y(IcefelixWindowManagerRectRaw* object);

/**
 * icefelix_window_manager_rect_raw_get_width
 * @object: a #IcefelixWindowManagerRectRaw.
 *
 * Gets the value of the width field of @object.
 *
 * Returns: the field value.
 */
double icefelix_window_manager_rect_raw_get_width(IcefelixWindowManagerRectRaw* object);

/**
 * icefelix_window_manager_rect_raw_get_height
 * @object: a #IcefelixWindowManagerRectRaw.
 *
 * Gets the value of the height field of @object.
 *
 * Returns: the field value.
 */
double icefelix_window_manager_rect_raw_get_height(IcefelixWindowManagerRectRaw* object);

/**
 * IcefelixWindowManagerWindowBoundsRaw:
 *
 */

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowBoundsRaw, icefelix_window_manager_window_bounds_raw, ICEFELIX_WINDOW_MANAGER, WINDOW_BOUNDS_RAW, GObject)

/**
 * icefelix_window_manager_window_bounds_raw_new:
 * position: field in this object.
 * size: field in this object.
 *
 * Creates a new #WindowBoundsRaw object.
 *
 * Returns: a new #IcefelixWindowManagerWindowBoundsRaw
 */
IcefelixWindowManagerWindowBoundsRaw* icefelix_window_manager_window_bounds_raw_new(IcefelixWindowManagerOffsetRaw* position, IcefelixWindowManagerSizeRaw* size);

/**
 * icefelix_window_manager_window_bounds_raw_get_position
 * @object: a #IcefelixWindowManagerWindowBoundsRaw.
 *
 * Gets the value of the position field of @object.
 *
 * Returns: the field value.
 */
IcefelixWindowManagerOffsetRaw* icefelix_window_manager_window_bounds_raw_get_position(IcefelixWindowManagerWindowBoundsRaw* object);

/**
 * icefelix_window_manager_window_bounds_raw_get_size
 * @object: a #IcefelixWindowManagerWindowBoundsRaw.
 *
 * Gets the value of the size field of @object.
 *
 * Returns: the field value.
 */
IcefelixWindowManagerSizeRaw* icefelix_window_manager_window_bounds_raw_get_size(IcefelixWindowManagerWindowBoundsRaw* object);

/**
 * IcefelixWindowManagerDisplayRaw:
 *
 */

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerDisplayRaw, icefelix_window_manager_display_raw, ICEFELIX_WINDOW_MANAGER, DISPLAY_RAW, GObject)

/**
 * icefelix_window_manager_display_raw_new:
 * id: field in this object.
 * name: field in this object.
 * bounds: field in this object.
 * work_area: field in this object.
 * physical_width_mm: field in this object.
 * physical_height_mm: field in this object.
 * dpi: field in this object.
 * scale_factor: field in this object.
 * is_primary: field in this object.
 * refresh_rate: field in this object.
 *
 * Creates a new #DisplayRaw object.
 *
 * Returns: a new #IcefelixWindowManagerDisplayRaw
 */
IcefelixWindowManagerDisplayRaw* icefelix_window_manager_display_raw_new(const gchar* id, const gchar* name, IcefelixWindowManagerRectRaw* bounds, IcefelixWindowManagerRectRaw* work_area, double* physical_width_mm, double* physical_height_mm, double* dpi, double scale_factor, gboolean is_primary, int64_t* refresh_rate);

/**
 * icefelix_window_manager_display_raw_get_id
 * @object: a #IcefelixWindowManagerDisplayRaw.
 *
 * Gets the value of the id field of @object.
 *
 * Returns: the field value.
 */
const gchar* icefelix_window_manager_display_raw_get_id(IcefelixWindowManagerDisplayRaw* object);

/**
 * icefelix_window_manager_display_raw_get_name
 * @object: a #IcefelixWindowManagerDisplayRaw.
 *
 * Gets the value of the name field of @object.
 *
 * Returns: the field value.
 */
const gchar* icefelix_window_manager_display_raw_get_name(IcefelixWindowManagerDisplayRaw* object);

/**
 * icefelix_window_manager_display_raw_get_bounds
 * @object: a #IcefelixWindowManagerDisplayRaw.
 *
 * Gets the value of the bounds field of @object.
 *
 * Returns: the field value.
 */
IcefelixWindowManagerRectRaw* icefelix_window_manager_display_raw_get_bounds(IcefelixWindowManagerDisplayRaw* object);

/**
 * icefelix_window_manager_display_raw_get_work_area
 * @object: a #IcefelixWindowManagerDisplayRaw.
 *
 * Gets the value of the workArea field of @object.
 *
 * Returns: the field value.
 */
IcefelixWindowManagerRectRaw* icefelix_window_manager_display_raw_get_work_area(IcefelixWindowManagerDisplayRaw* object);

/**
 * icefelix_window_manager_display_raw_get_physical_width_mm
 * @object: a #IcefelixWindowManagerDisplayRaw.
 *
 * Gets the value of the physicalWidthMm field of @object.
 *
 * Returns: the field value.
 */
double* icefelix_window_manager_display_raw_get_physical_width_mm(IcefelixWindowManagerDisplayRaw* object);

/**
 * icefelix_window_manager_display_raw_get_physical_height_mm
 * @object: a #IcefelixWindowManagerDisplayRaw.
 *
 * Gets the value of the physicalHeightMm field of @object.
 *
 * Returns: the field value.
 */
double* icefelix_window_manager_display_raw_get_physical_height_mm(IcefelixWindowManagerDisplayRaw* object);

/**
 * icefelix_window_manager_display_raw_get_dpi
 * @object: a #IcefelixWindowManagerDisplayRaw.
 *
 * Gets the value of the dpi field of @object.
 *
 * Returns: the field value.
 */
double* icefelix_window_manager_display_raw_get_dpi(IcefelixWindowManagerDisplayRaw* object);

/**
 * icefelix_window_manager_display_raw_get_scale_factor
 * @object: a #IcefelixWindowManagerDisplayRaw.
 *
 * Gets the value of the scaleFactor field of @object.
 *
 * Returns: the field value.
 */
double icefelix_window_manager_display_raw_get_scale_factor(IcefelixWindowManagerDisplayRaw* object);

/**
 * icefelix_window_manager_display_raw_get_is_primary
 * @object: a #IcefelixWindowManagerDisplayRaw.
 *
 * Gets the value of the isPrimary field of @object.
 *
 * Returns: the field value.
 */
gboolean icefelix_window_manager_display_raw_get_is_primary(IcefelixWindowManagerDisplayRaw* object);

/**
 * icefelix_window_manager_display_raw_get_refresh_rate
 * @object: a #IcefelixWindowManagerDisplayRaw.
 *
 * Gets the value of the refreshRate field of @object.
 *
 * Returns: the field value.
 */
int64_t* icefelix_window_manager_display_raw_get_refresh_rate(IcefelixWindowManagerDisplayRaw* object);

/**
 * IcefelixWindowManagerWindowSnapshotRaw:
 *
 */

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowSnapshotRaw, icefelix_window_manager_window_snapshot_raw, ICEFELIX_WINDOW_MANAGER, WINDOW_SNAPSHOT_RAW, GObject)

/**
 * icefelix_window_manager_window_snapshot_raw_new:
 * bounds: field in this object.
 * state: field in this object.
 * title: field in this object.
 * is_focused: field in this object.
 * always_on_top: field in this object.
 * skip_taskbar: field in this object.
 * resizable: field in this object.
 * movable: field in this object.
 * minimizable: field in this object.
 * maximizable: field in this object.
 * closable: field in this object.
 * frameless: field in this object.
 * title_bar_style: field in this object.
 * opacity: field in this object.
 * background_color_argb: field in this object.
 * has_shadow: field in this object.
 * prevent_close: field in this object.
 * current_display: field in this object.
 *
 * Creates a new #WindowSnapshotRaw object.
 *
 * Returns: a new #IcefelixWindowManagerWindowSnapshotRaw
 */
IcefelixWindowManagerWindowSnapshotRaw* icefelix_window_manager_window_snapshot_raw_new(IcefelixWindowManagerWindowBoundsRaw* bounds, IcefelixWindowManagerWindowStateRaw state, const gchar* title, gboolean is_focused, gboolean always_on_top, gboolean skip_taskbar, gboolean resizable, gboolean movable, gboolean minimizable, gboolean maximizable, gboolean closable, gboolean frameless, IcefelixWindowManagerTitleBarStyleRaw title_bar_style, double opacity, int64_t* background_color_argb, gboolean has_shadow, gboolean prevent_close, IcefelixWindowManagerDisplayRaw* current_display);

/**
 * icefelix_window_manager_window_snapshot_raw_get_bounds
 * @object: a #IcefelixWindowManagerWindowSnapshotRaw.
 *
 * Gets the value of the bounds field of @object.
 *
 * Returns: the field value.
 */
IcefelixWindowManagerWindowBoundsRaw* icefelix_window_manager_window_snapshot_raw_get_bounds(IcefelixWindowManagerWindowSnapshotRaw* object);

/**
 * icefelix_window_manager_window_snapshot_raw_get_state
 * @object: a #IcefelixWindowManagerWindowSnapshotRaw.
 *
 * Gets the value of the state field of @object.
 *
 * Returns: the field value.
 */
IcefelixWindowManagerWindowStateRaw icefelix_window_manager_window_snapshot_raw_get_state(IcefelixWindowManagerWindowSnapshotRaw* object);

/**
 * icefelix_window_manager_window_snapshot_raw_get_title
 * @object: a #IcefelixWindowManagerWindowSnapshotRaw.
 *
 * Gets the value of the title field of @object.
 *
 * Returns: the field value.
 */
const gchar* icefelix_window_manager_window_snapshot_raw_get_title(IcefelixWindowManagerWindowSnapshotRaw* object);

/**
 * icefelix_window_manager_window_snapshot_raw_get_is_focused
 * @object: a #IcefelixWindowManagerWindowSnapshotRaw.
 *
 * Gets the value of the isFocused field of @object.
 *
 * Returns: the field value.
 */
gboolean icefelix_window_manager_window_snapshot_raw_get_is_focused(IcefelixWindowManagerWindowSnapshotRaw* object);

/**
 * icefelix_window_manager_window_snapshot_raw_get_always_on_top
 * @object: a #IcefelixWindowManagerWindowSnapshotRaw.
 *
 * Gets the value of the alwaysOnTop field of @object.
 *
 * Returns: the field value.
 */
gboolean icefelix_window_manager_window_snapshot_raw_get_always_on_top(IcefelixWindowManagerWindowSnapshotRaw* object);

/**
 * icefelix_window_manager_window_snapshot_raw_get_skip_taskbar
 * @object: a #IcefelixWindowManagerWindowSnapshotRaw.
 *
 * Gets the value of the skipTaskbar field of @object.
 *
 * Returns: the field value.
 */
gboolean icefelix_window_manager_window_snapshot_raw_get_skip_taskbar(IcefelixWindowManagerWindowSnapshotRaw* object);

/**
 * icefelix_window_manager_window_snapshot_raw_get_resizable
 * @object: a #IcefelixWindowManagerWindowSnapshotRaw.
 *
 * Gets the value of the resizable field of @object.
 *
 * Returns: the field value.
 */
gboolean icefelix_window_manager_window_snapshot_raw_get_resizable(IcefelixWindowManagerWindowSnapshotRaw* object);

/**
 * icefelix_window_manager_window_snapshot_raw_get_movable
 * @object: a #IcefelixWindowManagerWindowSnapshotRaw.
 *
 * Gets the value of the movable field of @object.
 *
 * Returns: the field value.
 */
gboolean icefelix_window_manager_window_snapshot_raw_get_movable(IcefelixWindowManagerWindowSnapshotRaw* object);

/**
 * icefelix_window_manager_window_snapshot_raw_get_minimizable
 * @object: a #IcefelixWindowManagerWindowSnapshotRaw.
 *
 * Gets the value of the minimizable field of @object.
 *
 * Returns: the field value.
 */
gboolean icefelix_window_manager_window_snapshot_raw_get_minimizable(IcefelixWindowManagerWindowSnapshotRaw* object);

/**
 * icefelix_window_manager_window_snapshot_raw_get_maximizable
 * @object: a #IcefelixWindowManagerWindowSnapshotRaw.
 *
 * Gets the value of the maximizable field of @object.
 *
 * Returns: the field value.
 */
gboolean icefelix_window_manager_window_snapshot_raw_get_maximizable(IcefelixWindowManagerWindowSnapshotRaw* object);

/**
 * icefelix_window_manager_window_snapshot_raw_get_closable
 * @object: a #IcefelixWindowManagerWindowSnapshotRaw.
 *
 * Gets the value of the closable field of @object.
 *
 * Returns: the field value.
 */
gboolean icefelix_window_manager_window_snapshot_raw_get_closable(IcefelixWindowManagerWindowSnapshotRaw* object);

/**
 * icefelix_window_manager_window_snapshot_raw_get_frameless
 * @object: a #IcefelixWindowManagerWindowSnapshotRaw.
 *
 * Gets the value of the frameless field of @object.
 *
 * Returns: the field value.
 */
gboolean icefelix_window_manager_window_snapshot_raw_get_frameless(IcefelixWindowManagerWindowSnapshotRaw* object);

/**
 * icefelix_window_manager_window_snapshot_raw_get_title_bar_style
 * @object: a #IcefelixWindowManagerWindowSnapshotRaw.
 *
 * Gets the value of the titleBarStyle field of @object.
 *
 * Returns: the field value.
 */
IcefelixWindowManagerTitleBarStyleRaw icefelix_window_manager_window_snapshot_raw_get_title_bar_style(IcefelixWindowManagerWindowSnapshotRaw* object);

/**
 * icefelix_window_manager_window_snapshot_raw_get_opacity
 * @object: a #IcefelixWindowManagerWindowSnapshotRaw.
 *
 * Gets the value of the opacity field of @object.
 *
 * Returns: the field value.
 */
double icefelix_window_manager_window_snapshot_raw_get_opacity(IcefelixWindowManagerWindowSnapshotRaw* object);

/**
 * icefelix_window_manager_window_snapshot_raw_get_background_color_argb
 * @object: a #IcefelixWindowManagerWindowSnapshotRaw.
 *
 * Gets the value of the backgroundColorArgb field of @object.
 *
 * Returns: the field value.
 */
int64_t* icefelix_window_manager_window_snapshot_raw_get_background_color_argb(IcefelixWindowManagerWindowSnapshotRaw* object);

/**
 * icefelix_window_manager_window_snapshot_raw_get_has_shadow
 * @object: a #IcefelixWindowManagerWindowSnapshotRaw.
 *
 * Gets the value of the hasShadow field of @object.
 *
 * Returns: the field value.
 */
gboolean icefelix_window_manager_window_snapshot_raw_get_has_shadow(IcefelixWindowManagerWindowSnapshotRaw* object);

/**
 * icefelix_window_manager_window_snapshot_raw_get_prevent_close
 * @object: a #IcefelixWindowManagerWindowSnapshotRaw.
 *
 * Gets the value of the preventClose field of @object.
 *
 * Returns: the field value.
 */
gboolean icefelix_window_manager_window_snapshot_raw_get_prevent_close(IcefelixWindowManagerWindowSnapshotRaw* object);

/**
 * icefelix_window_manager_window_snapshot_raw_get_current_display
 * @object: a #IcefelixWindowManagerWindowSnapshotRaw.
 *
 * Gets the value of the currentDisplay field of @object.
 *
 * Returns: the field value.
 */
IcefelixWindowManagerDisplayRaw* icefelix_window_manager_window_snapshot_raw_get_current_display(IcefelixWindowManagerWindowSnapshotRaw* object);

/**
 * IcefelixWindowManagerPlatformInfoRaw:
 *
 */

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerPlatformInfoRaw, icefelix_window_manager_platform_info_raw, ICEFELIX_WINDOW_MANAGER, PLATFORM_INFO_RAW, GObject)

/**
 * icefelix_window_manager_platform_info_raw_new:
 * target: field in this object.
 * display_server: field in this object.
 * is_sandboxed: field in this object.
 *
 * Creates a new #PlatformInfoRaw object.
 *
 * Returns: a new #IcefelixWindowManagerPlatformInfoRaw
 */
IcefelixWindowManagerPlatformInfoRaw* icefelix_window_manager_platform_info_raw_new(const gchar* target, IcefelixWindowManagerDisplayServerRaw* display_server, gboolean is_sandboxed);

/**
 * icefelix_window_manager_platform_info_raw_get_target
 * @object: a #IcefelixWindowManagerPlatformInfoRaw.
 *
 * Gets the value of the target field of @object.
 *
 * Returns: the field value.
 */
const gchar* icefelix_window_manager_platform_info_raw_get_target(IcefelixWindowManagerPlatformInfoRaw* object);

/**
 * icefelix_window_manager_platform_info_raw_get_display_server
 * @object: a #IcefelixWindowManagerPlatformInfoRaw.
 *
 * Gets the value of the displayServer field of @object.
 *
 * Returns: the field value.
 */
IcefelixWindowManagerDisplayServerRaw* icefelix_window_manager_platform_info_raw_get_display_server(IcefelixWindowManagerPlatformInfoRaw* object);

/**
 * icefelix_window_manager_platform_info_raw_get_is_sandboxed
 * @object: a #IcefelixWindowManagerPlatformInfoRaw.
 *
 * Gets the value of the isSandboxed field of @object.
 *
 * Returns: the field value.
 */
gboolean icefelix_window_manager_platform_info_raw_get_is_sandboxed(IcefelixWindowManagerPlatformInfoRaw* object);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerMessageCodec, icefelix_window_manager_message_codec, ICEFELIX_WINDOW_MANAGER, MESSAGE_CODEC, FlStandardMessageCodec)

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApi, icefelix_window_manager_window_host_api, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiEnsureInitializedResponse, icefelix_window_manager_window_host_api_ensure_initialized_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_ENSURE_INITIALIZED_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_ensure_initialized_response_new:
 *
 * Creates a new response to WindowHostApi.ensureInitialized.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiEnsureInitializedResponse
 */
IcefelixWindowManagerWindowHostApiEnsureInitializedResponse* icefelix_window_manager_window_host_api_ensure_initialized_response_new(IcefelixWindowManagerWindowSnapshotRaw* return_value);

/**
 * icefelix_window_manager_window_host_api_ensure_initialized_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.ensureInitialized.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiEnsureInitializedResponse
 */
IcefelixWindowManagerWindowHostApiEnsureInitializedResponse* icefelix_window_manager_window_host_api_ensure_initialized_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiGetPlatformInfoResponse, icefelix_window_manager_window_host_api_get_platform_info_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_GET_PLATFORM_INFO_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_get_platform_info_response_new:
 *
 * Creates a new response to WindowHostApi.getPlatformInfo.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiGetPlatformInfoResponse
 */
IcefelixWindowManagerWindowHostApiGetPlatformInfoResponse* icefelix_window_manager_window_host_api_get_platform_info_response_new(IcefelixWindowManagerPlatformInfoRaw* return_value);

/**
 * icefelix_window_manager_window_host_api_get_platform_info_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.getPlatformInfo.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiGetPlatformInfoResponse
 */
IcefelixWindowManagerWindowHostApiGetPlatformInfoResponse* icefelix_window_manager_window_host_api_get_platform_info_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiGetBoundsResponse, icefelix_window_manager_window_host_api_get_bounds_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_GET_BOUNDS_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_get_bounds_response_new:
 *
 * Creates a new response to WindowHostApi.getBounds.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiGetBoundsResponse
 */
IcefelixWindowManagerWindowHostApiGetBoundsResponse* icefelix_window_manager_window_host_api_get_bounds_response_new(IcefelixWindowManagerWindowBoundsRaw* return_value);

/**
 * icefelix_window_manager_window_host_api_get_bounds_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.getBounds.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiGetBoundsResponse
 */
IcefelixWindowManagerWindowHostApiGetBoundsResponse* icefelix_window_manager_window_host_api_get_bounds_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiSetBoundsResponse, icefelix_window_manager_window_host_api_set_bounds_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SET_BOUNDS_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_set_bounds_response_new:
 *
 * Creates a new response to WindowHostApi.setBounds.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetBoundsResponse
 */
IcefelixWindowManagerWindowHostApiSetBoundsResponse* icefelix_window_manager_window_host_api_set_bounds_response_new();

/**
 * icefelix_window_manager_window_host_api_set_bounds_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.setBounds.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetBoundsResponse
 */
IcefelixWindowManagerWindowHostApiSetBoundsResponse* icefelix_window_manager_window_host_api_set_bounds_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiSetSizeResponse, icefelix_window_manager_window_host_api_set_size_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SET_SIZE_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_set_size_response_new:
 *
 * Creates a new response to WindowHostApi.setSize.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetSizeResponse
 */
IcefelixWindowManagerWindowHostApiSetSizeResponse* icefelix_window_manager_window_host_api_set_size_response_new();

/**
 * icefelix_window_manager_window_host_api_set_size_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.setSize.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetSizeResponse
 */
IcefelixWindowManagerWindowHostApiSetSizeResponse* icefelix_window_manager_window_host_api_set_size_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiSetMinSizeResponse, icefelix_window_manager_window_host_api_set_min_size_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SET_MIN_SIZE_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_set_min_size_response_new:
 *
 * Creates a new response to WindowHostApi.setMinSize.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetMinSizeResponse
 */
IcefelixWindowManagerWindowHostApiSetMinSizeResponse* icefelix_window_manager_window_host_api_set_min_size_response_new();

/**
 * icefelix_window_manager_window_host_api_set_min_size_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.setMinSize.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetMinSizeResponse
 */
IcefelixWindowManagerWindowHostApiSetMinSizeResponse* icefelix_window_manager_window_host_api_set_min_size_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiSetMaxSizeResponse, icefelix_window_manager_window_host_api_set_max_size_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SET_MAX_SIZE_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_set_max_size_response_new:
 *
 * Creates a new response to WindowHostApi.setMaxSize.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetMaxSizeResponse
 */
IcefelixWindowManagerWindowHostApiSetMaxSizeResponse* icefelix_window_manager_window_host_api_set_max_size_response_new();

/**
 * icefelix_window_manager_window_host_api_set_max_size_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.setMaxSize.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetMaxSizeResponse
 */
IcefelixWindowManagerWindowHostApiSetMaxSizeResponse* icefelix_window_manager_window_host_api_set_max_size_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiSetPositionResponse, icefelix_window_manager_window_host_api_set_position_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SET_POSITION_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_set_position_response_new:
 *
 * Creates a new response to WindowHostApi.setPosition.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetPositionResponse
 */
IcefelixWindowManagerWindowHostApiSetPositionResponse* icefelix_window_manager_window_host_api_set_position_response_new();

/**
 * icefelix_window_manager_window_host_api_set_position_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.setPosition.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetPositionResponse
 */
IcefelixWindowManagerWindowHostApiSetPositionResponse* icefelix_window_manager_window_host_api_set_position_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiCenterResponse, icefelix_window_manager_window_host_api_center_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_CENTER_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_center_response_new:
 *
 * Creates a new response to WindowHostApi.center.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiCenterResponse
 */
IcefelixWindowManagerWindowHostApiCenterResponse* icefelix_window_manager_window_host_api_center_response_new();

/**
 * icefelix_window_manager_window_host_api_center_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.center.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiCenterResponse
 */
IcefelixWindowManagerWindowHostApiCenterResponse* icefelix_window_manager_window_host_api_center_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiMoveToDisplayResponse, icefelix_window_manager_window_host_api_move_to_display_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_MOVE_TO_DISPLAY_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_move_to_display_response_new:
 *
 * Creates a new response to WindowHostApi.moveToDisplay.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiMoveToDisplayResponse
 */
IcefelixWindowManagerWindowHostApiMoveToDisplayResponse* icefelix_window_manager_window_host_api_move_to_display_response_new();

/**
 * icefelix_window_manager_window_host_api_move_to_display_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.moveToDisplay.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiMoveToDisplayResponse
 */
IcefelixWindowManagerWindowHostApiMoveToDisplayResponse* icefelix_window_manager_window_host_api_move_to_display_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiMinimizeResponse, icefelix_window_manager_window_host_api_minimize_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_MINIMIZE_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_minimize_response_new:
 *
 * Creates a new response to WindowHostApi.minimize.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiMinimizeResponse
 */
IcefelixWindowManagerWindowHostApiMinimizeResponse* icefelix_window_manager_window_host_api_minimize_response_new();

/**
 * icefelix_window_manager_window_host_api_minimize_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.minimize.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiMinimizeResponse
 */
IcefelixWindowManagerWindowHostApiMinimizeResponse* icefelix_window_manager_window_host_api_minimize_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiMaximizeResponse, icefelix_window_manager_window_host_api_maximize_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_MAXIMIZE_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_maximize_response_new:
 *
 * Creates a new response to WindowHostApi.maximize.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiMaximizeResponse
 */
IcefelixWindowManagerWindowHostApiMaximizeResponse* icefelix_window_manager_window_host_api_maximize_response_new();

/**
 * icefelix_window_manager_window_host_api_maximize_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.maximize.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiMaximizeResponse
 */
IcefelixWindowManagerWindowHostApiMaximizeResponse* icefelix_window_manager_window_host_api_maximize_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiUnmaximizeResponse, icefelix_window_manager_window_host_api_unmaximize_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_UNMAXIMIZE_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_unmaximize_response_new:
 *
 * Creates a new response to WindowHostApi.unmaximize.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiUnmaximizeResponse
 */
IcefelixWindowManagerWindowHostApiUnmaximizeResponse* icefelix_window_manager_window_host_api_unmaximize_response_new();

/**
 * icefelix_window_manager_window_host_api_unmaximize_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.unmaximize.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiUnmaximizeResponse
 */
IcefelixWindowManagerWindowHostApiUnmaximizeResponse* icefelix_window_manager_window_host_api_unmaximize_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiRestoreResponse, icefelix_window_manager_window_host_api_restore_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_RESTORE_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_restore_response_new:
 *
 * Creates a new response to WindowHostApi.restore.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiRestoreResponse
 */
IcefelixWindowManagerWindowHostApiRestoreResponse* icefelix_window_manager_window_host_api_restore_response_new();

/**
 * icefelix_window_manager_window_host_api_restore_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.restore.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiRestoreResponse
 */
IcefelixWindowManagerWindowHostApiRestoreResponse* icefelix_window_manager_window_host_api_restore_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiHideResponse, icefelix_window_manager_window_host_api_hide_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_HIDE_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_hide_response_new:
 *
 * Creates a new response to WindowHostApi.hide.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiHideResponse
 */
IcefelixWindowManagerWindowHostApiHideResponse* icefelix_window_manager_window_host_api_hide_response_new();

/**
 * icefelix_window_manager_window_host_api_hide_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.hide.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiHideResponse
 */
IcefelixWindowManagerWindowHostApiHideResponse* icefelix_window_manager_window_host_api_hide_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiShowResponse, icefelix_window_manager_window_host_api_show_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SHOW_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_show_response_new:
 *
 * Creates a new response to WindowHostApi.show.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiShowResponse
 */
IcefelixWindowManagerWindowHostApiShowResponse* icefelix_window_manager_window_host_api_show_response_new();

/**
 * icefelix_window_manager_window_host_api_show_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.show.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiShowResponse
 */
IcefelixWindowManagerWindowHostApiShowResponse* icefelix_window_manager_window_host_api_show_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiFullscreenResponse, icefelix_window_manager_window_host_api_fullscreen_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_FULLSCREEN_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_fullscreen_response_new:
 *
 * Creates a new response to WindowHostApi.fullscreen.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiFullscreenResponse
 */
IcefelixWindowManagerWindowHostApiFullscreenResponse* icefelix_window_manager_window_host_api_fullscreen_response_new();

/**
 * icefelix_window_manager_window_host_api_fullscreen_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.fullscreen.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiFullscreenResponse
 */
IcefelixWindowManagerWindowHostApiFullscreenResponse* icefelix_window_manager_window_host_api_fullscreen_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiExitFullscreenResponse, icefelix_window_manager_window_host_api_exit_fullscreen_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_EXIT_FULLSCREEN_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_exit_fullscreen_response_new:
 *
 * Creates a new response to WindowHostApi.exitFullscreen.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiExitFullscreenResponse
 */
IcefelixWindowManagerWindowHostApiExitFullscreenResponse* icefelix_window_manager_window_host_api_exit_fullscreen_response_new();

/**
 * icefelix_window_manager_window_host_api_exit_fullscreen_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.exitFullscreen.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiExitFullscreenResponse
 */
IcefelixWindowManagerWindowHostApiExitFullscreenResponse* icefelix_window_manager_window_host_api_exit_fullscreen_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiFocusResponse, icefelix_window_manager_window_host_api_focus_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_FOCUS_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_focus_response_new:
 *
 * Creates a new response to WindowHostApi.focus.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiFocusResponse
 */
IcefelixWindowManagerWindowHostApiFocusResponse* icefelix_window_manager_window_host_api_focus_response_new();

/**
 * icefelix_window_manager_window_host_api_focus_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.focus.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiFocusResponse
 */
IcefelixWindowManagerWindowHostApiFocusResponse* icefelix_window_manager_window_host_api_focus_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiBlurResponse, icefelix_window_manager_window_host_api_blur_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_BLUR_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_blur_response_new:
 *
 * Creates a new response to WindowHostApi.blur.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiBlurResponse
 */
IcefelixWindowManagerWindowHostApiBlurResponse* icefelix_window_manager_window_host_api_blur_response_new();

/**
 * icefelix_window_manager_window_host_api_blur_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.blur.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiBlurResponse
 */
IcefelixWindowManagerWindowHostApiBlurResponse* icefelix_window_manager_window_host_api_blur_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiStartDragResponse, icefelix_window_manager_window_host_api_start_drag_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_START_DRAG_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_start_drag_response_new:
 *
 * Creates a new response to WindowHostApi.startDrag.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiStartDragResponse
 */
IcefelixWindowManagerWindowHostApiStartDragResponse* icefelix_window_manager_window_host_api_start_drag_response_new();

/**
 * icefelix_window_manager_window_host_api_start_drag_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.startDrag.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiStartDragResponse
 */
IcefelixWindowManagerWindowHostApiStartDragResponse* icefelix_window_manager_window_host_api_start_drag_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiStartResizeResponse, icefelix_window_manager_window_host_api_start_resize_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_START_RESIZE_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_start_resize_response_new:
 *
 * Creates a new response to WindowHostApi.startResize.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiStartResizeResponse
 */
IcefelixWindowManagerWindowHostApiStartResizeResponse* icefelix_window_manager_window_host_api_start_resize_response_new();

/**
 * icefelix_window_manager_window_host_api_start_resize_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.startResize.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiStartResizeResponse
 */
IcefelixWindowManagerWindowHostApiStartResizeResponse* icefelix_window_manager_window_host_api_start_resize_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiCloseResponse, icefelix_window_manager_window_host_api_close_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_CLOSE_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_close_response_new:
 *
 * Creates a new response to WindowHostApi.close.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiCloseResponse
 */
IcefelixWindowManagerWindowHostApiCloseResponse* icefelix_window_manager_window_host_api_close_response_new();

/**
 * icefelix_window_manager_window_host_api_close_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.close.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiCloseResponse
 */
IcefelixWindowManagerWindowHostApiCloseResponse* icefelix_window_manager_window_host_api_close_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiDestroyResponse, icefelix_window_manager_window_host_api_destroy_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_DESTROY_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_destroy_response_new:
 *
 * Creates a new response to WindowHostApi.destroy.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiDestroyResponse
 */
IcefelixWindowManagerWindowHostApiDestroyResponse* icefelix_window_manager_window_host_api_destroy_response_new();

/**
 * icefelix_window_manager_window_host_api_destroy_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.destroy.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiDestroyResponse
 */
IcefelixWindowManagerWindowHostApiDestroyResponse* icefelix_window_manager_window_host_api_destroy_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiSetTitleResponse, icefelix_window_manager_window_host_api_set_title_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SET_TITLE_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_set_title_response_new:
 *
 * Creates a new response to WindowHostApi.setTitle.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetTitleResponse
 */
IcefelixWindowManagerWindowHostApiSetTitleResponse* icefelix_window_manager_window_host_api_set_title_response_new();

/**
 * icefelix_window_manager_window_host_api_set_title_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.setTitle.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetTitleResponse
 */
IcefelixWindowManagerWindowHostApiSetTitleResponse* icefelix_window_manager_window_host_api_set_title_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiSetAlwaysOnTopResponse, icefelix_window_manager_window_host_api_set_always_on_top_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SET_ALWAYS_ON_TOP_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_set_always_on_top_response_new:
 *
 * Creates a new response to WindowHostApi.setAlwaysOnTop.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetAlwaysOnTopResponse
 */
IcefelixWindowManagerWindowHostApiSetAlwaysOnTopResponse* icefelix_window_manager_window_host_api_set_always_on_top_response_new();

/**
 * icefelix_window_manager_window_host_api_set_always_on_top_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.setAlwaysOnTop.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetAlwaysOnTopResponse
 */
IcefelixWindowManagerWindowHostApiSetAlwaysOnTopResponse* icefelix_window_manager_window_host_api_set_always_on_top_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiSetSkipTaskbarResponse, icefelix_window_manager_window_host_api_set_skip_taskbar_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SET_SKIP_TASKBAR_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_set_skip_taskbar_response_new:
 *
 * Creates a new response to WindowHostApi.setSkipTaskbar.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetSkipTaskbarResponse
 */
IcefelixWindowManagerWindowHostApiSetSkipTaskbarResponse* icefelix_window_manager_window_host_api_set_skip_taskbar_response_new();

/**
 * icefelix_window_manager_window_host_api_set_skip_taskbar_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.setSkipTaskbar.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetSkipTaskbarResponse
 */
IcefelixWindowManagerWindowHostApiSetSkipTaskbarResponse* icefelix_window_manager_window_host_api_set_skip_taskbar_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiSetResizableResponse, icefelix_window_manager_window_host_api_set_resizable_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SET_RESIZABLE_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_set_resizable_response_new:
 *
 * Creates a new response to WindowHostApi.setResizable.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetResizableResponse
 */
IcefelixWindowManagerWindowHostApiSetResizableResponse* icefelix_window_manager_window_host_api_set_resizable_response_new();

/**
 * icefelix_window_manager_window_host_api_set_resizable_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.setResizable.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetResizableResponse
 */
IcefelixWindowManagerWindowHostApiSetResizableResponse* icefelix_window_manager_window_host_api_set_resizable_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiSetMovableResponse, icefelix_window_manager_window_host_api_set_movable_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SET_MOVABLE_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_set_movable_response_new:
 *
 * Creates a new response to WindowHostApi.setMovable.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetMovableResponse
 */
IcefelixWindowManagerWindowHostApiSetMovableResponse* icefelix_window_manager_window_host_api_set_movable_response_new();

/**
 * icefelix_window_manager_window_host_api_set_movable_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.setMovable.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetMovableResponse
 */
IcefelixWindowManagerWindowHostApiSetMovableResponse* icefelix_window_manager_window_host_api_set_movable_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiSetMinimizableResponse, icefelix_window_manager_window_host_api_set_minimizable_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SET_MINIMIZABLE_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_set_minimizable_response_new:
 *
 * Creates a new response to WindowHostApi.setMinimizable.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetMinimizableResponse
 */
IcefelixWindowManagerWindowHostApiSetMinimizableResponse* icefelix_window_manager_window_host_api_set_minimizable_response_new();

/**
 * icefelix_window_manager_window_host_api_set_minimizable_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.setMinimizable.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetMinimizableResponse
 */
IcefelixWindowManagerWindowHostApiSetMinimizableResponse* icefelix_window_manager_window_host_api_set_minimizable_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiSetMaximizableResponse, icefelix_window_manager_window_host_api_set_maximizable_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SET_MAXIMIZABLE_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_set_maximizable_response_new:
 *
 * Creates a new response to WindowHostApi.setMaximizable.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetMaximizableResponse
 */
IcefelixWindowManagerWindowHostApiSetMaximizableResponse* icefelix_window_manager_window_host_api_set_maximizable_response_new();

/**
 * icefelix_window_manager_window_host_api_set_maximizable_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.setMaximizable.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetMaximizableResponse
 */
IcefelixWindowManagerWindowHostApiSetMaximizableResponse* icefelix_window_manager_window_host_api_set_maximizable_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiSetClosableResponse, icefelix_window_manager_window_host_api_set_closable_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SET_CLOSABLE_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_set_closable_response_new:
 *
 * Creates a new response to WindowHostApi.setClosable.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetClosableResponse
 */
IcefelixWindowManagerWindowHostApiSetClosableResponse* icefelix_window_manager_window_host_api_set_closable_response_new();

/**
 * icefelix_window_manager_window_host_api_set_closable_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.setClosable.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetClosableResponse
 */
IcefelixWindowManagerWindowHostApiSetClosableResponse* icefelix_window_manager_window_host_api_set_closable_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiSetFramelessResponse, icefelix_window_manager_window_host_api_set_frameless_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SET_FRAMELESS_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_set_frameless_response_new:
 *
 * Creates a new response to WindowHostApi.setFrameless.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetFramelessResponse
 */
IcefelixWindowManagerWindowHostApiSetFramelessResponse* icefelix_window_manager_window_host_api_set_frameless_response_new();

/**
 * icefelix_window_manager_window_host_api_set_frameless_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.setFrameless.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetFramelessResponse
 */
IcefelixWindowManagerWindowHostApiSetFramelessResponse* icefelix_window_manager_window_host_api_set_frameless_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiSetTitleBarStyleResponse, icefelix_window_manager_window_host_api_set_title_bar_style_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SET_TITLE_BAR_STYLE_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_set_title_bar_style_response_new:
 *
 * Creates a new response to WindowHostApi.setTitleBarStyle.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetTitleBarStyleResponse
 */
IcefelixWindowManagerWindowHostApiSetTitleBarStyleResponse* icefelix_window_manager_window_host_api_set_title_bar_style_response_new();

/**
 * icefelix_window_manager_window_host_api_set_title_bar_style_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.setTitleBarStyle.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetTitleBarStyleResponse
 */
IcefelixWindowManagerWindowHostApiSetTitleBarStyleResponse* icefelix_window_manager_window_host_api_set_title_bar_style_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiSetOpacityResponse, icefelix_window_manager_window_host_api_set_opacity_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SET_OPACITY_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_set_opacity_response_new:
 *
 * Creates a new response to WindowHostApi.setOpacity.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetOpacityResponse
 */
IcefelixWindowManagerWindowHostApiSetOpacityResponse* icefelix_window_manager_window_host_api_set_opacity_response_new();

/**
 * icefelix_window_manager_window_host_api_set_opacity_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.setOpacity.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetOpacityResponse
 */
IcefelixWindowManagerWindowHostApiSetOpacityResponse* icefelix_window_manager_window_host_api_set_opacity_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiSetBackgroundColorResponse, icefelix_window_manager_window_host_api_set_background_color_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SET_BACKGROUND_COLOR_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_set_background_color_response_new:
 *
 * Creates a new response to WindowHostApi.setBackgroundColor.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetBackgroundColorResponse
 */
IcefelixWindowManagerWindowHostApiSetBackgroundColorResponse* icefelix_window_manager_window_host_api_set_background_color_response_new();

/**
 * icefelix_window_manager_window_host_api_set_background_color_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.setBackgroundColor.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetBackgroundColorResponse
 */
IcefelixWindowManagerWindowHostApiSetBackgroundColorResponse* icefelix_window_manager_window_host_api_set_background_color_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiSetHasShadowResponse, icefelix_window_manager_window_host_api_set_has_shadow_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SET_HAS_SHADOW_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_set_has_shadow_response_new:
 *
 * Creates a new response to WindowHostApi.setHasShadow.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetHasShadowResponse
 */
IcefelixWindowManagerWindowHostApiSetHasShadowResponse* icefelix_window_manager_window_host_api_set_has_shadow_response_new();

/**
 * icefelix_window_manager_window_host_api_set_has_shadow_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.setHasShadow.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetHasShadowResponse
 */
IcefelixWindowManagerWindowHostApiSetHasShadowResponse* icefelix_window_manager_window_host_api_set_has_shadow_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiSetIconResponse, icefelix_window_manager_window_host_api_set_icon_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SET_ICON_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_set_icon_response_new:
 *
 * Creates a new response to WindowHostApi.setIcon.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetIconResponse
 */
IcefelixWindowManagerWindowHostApiSetIconResponse* icefelix_window_manager_window_host_api_set_icon_response_new();

/**
 * icefelix_window_manager_window_host_api_set_icon_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.setIcon.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetIconResponse
 */
IcefelixWindowManagerWindowHostApiSetIconResponse* icefelix_window_manager_window_host_api_set_icon_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiSetShapeResponse, icefelix_window_manager_window_host_api_set_shape_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SET_SHAPE_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_set_shape_response_new:
 *
 * Creates a new response to WindowHostApi.setShape.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetShapeResponse
 */
IcefelixWindowManagerWindowHostApiSetShapeResponse* icefelix_window_manager_window_host_api_set_shape_response_new();

/**
 * icefelix_window_manager_window_host_api_set_shape_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.setShape.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetShapeResponse
 */
IcefelixWindowManagerWindowHostApiSetShapeResponse* icefelix_window_manager_window_host_api_set_shape_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiSetPreventCloseResponse, icefelix_window_manager_window_host_api_set_prevent_close_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_SET_PREVENT_CLOSE_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_set_prevent_close_response_new:
 *
 * Creates a new response to WindowHostApi.setPreventClose.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetPreventCloseResponse
 */
IcefelixWindowManagerWindowHostApiSetPreventCloseResponse* icefelix_window_manager_window_host_api_set_prevent_close_response_new();

/**
 * icefelix_window_manager_window_host_api_set_prevent_close_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.setPreventClose.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiSetPreventCloseResponse
 */
IcefelixWindowManagerWindowHostApiSetPreventCloseResponse* icefelix_window_manager_window_host_api_set_prevent_close_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiListDisplaysResponse, icefelix_window_manager_window_host_api_list_displays_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_LIST_DISPLAYS_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_list_displays_response_new:
 *
 * Creates a new response to WindowHostApi.listDisplays.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiListDisplaysResponse
 */
IcefelixWindowManagerWindowHostApiListDisplaysResponse* icefelix_window_manager_window_host_api_list_displays_response_new(FlValue* return_value);

/**
 * icefelix_window_manager_window_host_api_list_displays_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.listDisplays.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiListDisplaysResponse
 */
IcefelixWindowManagerWindowHostApiListDisplaysResponse* icefelix_window_manager_window_host_api_list_displays_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiGetCurrentDisplayResponse, icefelix_window_manager_window_host_api_get_current_display_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_GET_CURRENT_DISPLAY_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_get_current_display_response_new:
 *
 * Creates a new response to WindowHostApi.getCurrentDisplay.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiGetCurrentDisplayResponse
 */
IcefelixWindowManagerWindowHostApiGetCurrentDisplayResponse* icefelix_window_manager_window_host_api_get_current_display_response_new(IcefelixWindowManagerDisplayRaw* return_value);

/**
 * icefelix_window_manager_window_host_api_get_current_display_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.getCurrentDisplay.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiGetCurrentDisplayResponse
 */
IcefelixWindowManagerWindowHostApiGetCurrentDisplayResponse* icefelix_window_manager_window_host_api_get_current_display_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowHostApiGetPrimaryDisplayResponse, icefelix_window_manager_window_host_api_get_primary_display_response, ICEFELIX_WINDOW_MANAGER, WINDOW_HOST_API_GET_PRIMARY_DISPLAY_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_host_api_get_primary_display_response_new:
 *
 * Creates a new response to WindowHostApi.getPrimaryDisplay.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiGetPrimaryDisplayResponse
 */
IcefelixWindowManagerWindowHostApiGetPrimaryDisplayResponse* icefelix_window_manager_window_host_api_get_primary_display_response_new(IcefelixWindowManagerDisplayRaw* return_value);

/**
 * icefelix_window_manager_window_host_api_get_primary_display_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to WindowHostApi.getPrimaryDisplay.
 *
 * Returns: a new #IcefelixWindowManagerWindowHostApiGetPrimaryDisplayResponse
 */
IcefelixWindowManagerWindowHostApiGetPrimaryDisplayResponse* icefelix_window_manager_window_host_api_get_primary_display_response_new_error(const gchar* code, const gchar* message, FlValue* details);

/**
 * IcefelixWindowManagerWindowHostApiVTable:
 *
 * Table of functions exposed by WindowHostApi to be implemented by the API provider.
 */
typedef struct {
  IcefelixWindowManagerWindowHostApiEnsureInitializedResponse* (*ensure_initialized)(gpointer user_data);
  IcefelixWindowManagerWindowHostApiGetPlatformInfoResponse* (*get_platform_info)(gpointer user_data);
  IcefelixWindowManagerWindowHostApiGetBoundsResponse* (*get_bounds)(gpointer user_data);
  IcefelixWindowManagerWindowHostApiSetBoundsResponse* (*set_bounds)(IcefelixWindowManagerWindowBoundsRaw* bounds, const gchar* display_id, gpointer user_data);
  IcefelixWindowManagerWindowHostApiSetSizeResponse* (*set_size)(IcefelixWindowManagerSizeRaw* size, gpointer user_data);
  IcefelixWindowManagerWindowHostApiSetMinSizeResponse* (*set_min_size)(IcefelixWindowManagerSizeRaw* size, gpointer user_data);
  IcefelixWindowManagerWindowHostApiSetMaxSizeResponse* (*set_max_size)(IcefelixWindowManagerSizeRaw* size, gpointer user_data);
  IcefelixWindowManagerWindowHostApiSetPositionResponse* (*set_position)(IcefelixWindowManagerOffsetRaw* position, gpointer user_data);
  IcefelixWindowManagerWindowHostApiCenterResponse* (*center)(gpointer user_data);
  IcefelixWindowManagerWindowHostApiMoveToDisplayResponse* (*move_to_display)(const gchar* display_id, gpointer user_data);
  IcefelixWindowManagerWindowHostApiMinimizeResponse* (*minimize)(gpointer user_data);
  IcefelixWindowManagerWindowHostApiMaximizeResponse* (*maximize)(gpointer user_data);
  IcefelixWindowManagerWindowHostApiUnmaximizeResponse* (*unmaximize)(gpointer user_data);
  IcefelixWindowManagerWindowHostApiRestoreResponse* (*restore)(gpointer user_data);
  IcefelixWindowManagerWindowHostApiHideResponse* (*hide)(gpointer user_data);
  IcefelixWindowManagerWindowHostApiShowResponse* (*show)(gpointer user_data);
  IcefelixWindowManagerWindowHostApiFullscreenResponse* (*fullscreen)(gpointer user_data);
  IcefelixWindowManagerWindowHostApiExitFullscreenResponse* (*exit_fullscreen)(gpointer user_data);
  IcefelixWindowManagerWindowHostApiFocusResponse* (*focus)(gpointer user_data);
  IcefelixWindowManagerWindowHostApiBlurResponse* (*blur)(gpointer user_data);
  IcefelixWindowManagerWindowHostApiStartDragResponse* (*start_drag)(gpointer user_data);
  IcefelixWindowManagerWindowHostApiStartResizeResponse* (*start_resize)(IcefelixWindowManagerResizeDirectionRaw direction, gpointer user_data);
  IcefelixWindowManagerWindowHostApiCloseResponse* (*close)(gpointer user_data);
  IcefelixWindowManagerWindowHostApiDestroyResponse* (*destroy)(gpointer user_data);
  IcefelixWindowManagerWindowHostApiSetTitleResponse* (*set_title)(const gchar* title, gpointer user_data);
  IcefelixWindowManagerWindowHostApiSetAlwaysOnTopResponse* (*set_always_on_top)(gboolean value, gpointer user_data);
  IcefelixWindowManagerWindowHostApiSetSkipTaskbarResponse* (*set_skip_taskbar)(gboolean value, gpointer user_data);
  IcefelixWindowManagerWindowHostApiSetResizableResponse* (*set_resizable)(gboolean value, gpointer user_data);
  IcefelixWindowManagerWindowHostApiSetMovableResponse* (*set_movable)(gboolean value, gpointer user_data);
  IcefelixWindowManagerWindowHostApiSetMinimizableResponse* (*set_minimizable)(gboolean value, gpointer user_data);
  IcefelixWindowManagerWindowHostApiSetMaximizableResponse* (*set_maximizable)(gboolean value, gpointer user_data);
  IcefelixWindowManagerWindowHostApiSetClosableResponse* (*set_closable)(gboolean value, gpointer user_data);
  IcefelixWindowManagerWindowHostApiSetFramelessResponse* (*set_frameless)(gboolean value, gpointer user_data);
  IcefelixWindowManagerWindowHostApiSetTitleBarStyleResponse* (*set_title_bar_style)(IcefelixWindowManagerTitleBarStyleRaw style, gpointer user_data);
  IcefelixWindowManagerWindowHostApiSetOpacityResponse* (*set_opacity)(double opacity, gpointer user_data);
  IcefelixWindowManagerWindowHostApiSetBackgroundColorResponse* (*set_background_color)(int64_t argb, gpointer user_data);
  IcefelixWindowManagerWindowHostApiSetHasShadowResponse* (*set_has_shadow)(gboolean value, gpointer user_data);
  IcefelixWindowManagerWindowHostApiSetIconResponse* (*set_icon)(const gchar* filesystem_path, gpointer user_data);
  IcefelixWindowManagerWindowHostApiSetShapeResponse* (*set_shape)(FlValue* points, gpointer user_data);
  IcefelixWindowManagerWindowHostApiSetPreventCloseResponse* (*set_prevent_close)(gboolean value, gpointer user_data);
  IcefelixWindowManagerWindowHostApiListDisplaysResponse* (*list_displays)(gpointer user_data);
  IcefelixWindowManagerWindowHostApiGetCurrentDisplayResponse* (*get_current_display)(gpointer user_data);
  IcefelixWindowManagerWindowHostApiGetPrimaryDisplayResponse* (*get_primary_display)(gpointer user_data);
} IcefelixWindowManagerWindowHostApiVTable;

/**
 * icefelix_window_manager_window_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the WindowHostApi API.
 */
void icefelix_window_manager_window_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const IcefelixWindowManagerWindowHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * icefelix_window_manager_window_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the WindowHostApi API.
 */
void icefelix_window_manager_window_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowFlutterApiOnSnapshotChangedResponse, icefelix_window_manager_window_flutter_api_on_snapshot_changed_response, ICEFELIX_WINDOW_MANAGER, WINDOW_FLUTTER_API_ON_SNAPSHOT_CHANGED_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_flutter_api_on_snapshot_changed_response_is_error:
 * @response: a #IcefelixWindowManagerWindowFlutterApiOnSnapshotChangedResponse.
 *
 * Checks if a response to WindowFlutterApi.onSnapshotChanged is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean icefelix_window_manager_window_flutter_api_on_snapshot_changed_response_is_error(IcefelixWindowManagerWindowFlutterApiOnSnapshotChangedResponse* response);

/**
 * icefelix_window_manager_window_flutter_api_on_snapshot_changed_response_get_error_code:
 * @response: a #IcefelixWindowManagerWindowFlutterApiOnSnapshotChangedResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* icefelix_window_manager_window_flutter_api_on_snapshot_changed_response_get_error_code(IcefelixWindowManagerWindowFlutterApiOnSnapshotChangedResponse* response);

/**
 * icefelix_window_manager_window_flutter_api_on_snapshot_changed_response_get_error_message:
 * @response: a #IcefelixWindowManagerWindowFlutterApiOnSnapshotChangedResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* icefelix_window_manager_window_flutter_api_on_snapshot_changed_response_get_error_message(IcefelixWindowManagerWindowFlutterApiOnSnapshotChangedResponse* response);

/**
 * icefelix_window_manager_window_flutter_api_on_snapshot_changed_response_get_error_details:
 * @response: a #IcefelixWindowManagerWindowFlutterApiOnSnapshotChangedResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* icefelix_window_manager_window_flutter_api_on_snapshot_changed_response_get_error_details(IcefelixWindowManagerWindowFlutterApiOnSnapshotChangedResponse* response);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowFlutterApiOnDisplaysChangedResponse, icefelix_window_manager_window_flutter_api_on_displays_changed_response, ICEFELIX_WINDOW_MANAGER, WINDOW_FLUTTER_API_ON_DISPLAYS_CHANGED_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_flutter_api_on_displays_changed_response_is_error:
 * @response: a #IcefelixWindowManagerWindowFlutterApiOnDisplaysChangedResponse.
 *
 * Checks if a response to WindowFlutterApi.onDisplaysChanged is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean icefelix_window_manager_window_flutter_api_on_displays_changed_response_is_error(IcefelixWindowManagerWindowFlutterApiOnDisplaysChangedResponse* response);

/**
 * icefelix_window_manager_window_flutter_api_on_displays_changed_response_get_error_code:
 * @response: a #IcefelixWindowManagerWindowFlutterApiOnDisplaysChangedResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* icefelix_window_manager_window_flutter_api_on_displays_changed_response_get_error_code(IcefelixWindowManagerWindowFlutterApiOnDisplaysChangedResponse* response);

/**
 * icefelix_window_manager_window_flutter_api_on_displays_changed_response_get_error_message:
 * @response: a #IcefelixWindowManagerWindowFlutterApiOnDisplaysChangedResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* icefelix_window_manager_window_flutter_api_on_displays_changed_response_get_error_message(IcefelixWindowManagerWindowFlutterApiOnDisplaysChangedResponse* response);

/**
 * icefelix_window_manager_window_flutter_api_on_displays_changed_response_get_error_details:
 * @response: a #IcefelixWindowManagerWindowFlutterApiOnDisplaysChangedResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* icefelix_window_manager_window_flutter_api_on_displays_changed_response_get_error_details(IcefelixWindowManagerWindowFlutterApiOnDisplaysChangedResponse* response);

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowFlutterApiOnCloseRequestResponse, icefelix_window_manager_window_flutter_api_on_close_request_response, ICEFELIX_WINDOW_MANAGER, WINDOW_FLUTTER_API_ON_CLOSE_REQUEST_RESPONSE, GObject)

/**
 * icefelix_window_manager_window_flutter_api_on_close_request_response_is_error:
 * @response: a #IcefelixWindowManagerWindowFlutterApiOnCloseRequestResponse.
 *
 * Checks if a response to WindowFlutterApi.onCloseRequest is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean icefelix_window_manager_window_flutter_api_on_close_request_response_is_error(IcefelixWindowManagerWindowFlutterApiOnCloseRequestResponse* response);

/**
 * icefelix_window_manager_window_flutter_api_on_close_request_response_get_error_code:
 * @response: a #IcefelixWindowManagerWindowFlutterApiOnCloseRequestResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* icefelix_window_manager_window_flutter_api_on_close_request_response_get_error_code(IcefelixWindowManagerWindowFlutterApiOnCloseRequestResponse* response);

/**
 * icefelix_window_manager_window_flutter_api_on_close_request_response_get_error_message:
 * @response: a #IcefelixWindowManagerWindowFlutterApiOnCloseRequestResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* icefelix_window_manager_window_flutter_api_on_close_request_response_get_error_message(IcefelixWindowManagerWindowFlutterApiOnCloseRequestResponse* response);

/**
 * icefelix_window_manager_window_flutter_api_on_close_request_response_get_error_details:
 * @response: a #IcefelixWindowManagerWindowFlutterApiOnCloseRequestResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* icefelix_window_manager_window_flutter_api_on_close_request_response_get_error_details(IcefelixWindowManagerWindowFlutterApiOnCloseRequestResponse* response);

/**
 * icefelix_window_manager_window_flutter_api_on_close_request_response_get_return_value:
 * @response: a #IcefelixWindowManagerWindowFlutterApiOnCloseRequestResponse.
 *
 * Get the return value for this response.
 *
 * Returns: a return value.
 */
gboolean icefelix_window_manager_window_flutter_api_on_close_request_response_get_return_value(IcefelixWindowManagerWindowFlutterApiOnCloseRequestResponse* response);

/**
 * IcefelixWindowManagerWindowFlutterApi:
 *
 */

G_DECLARE_FINAL_TYPE(IcefelixWindowManagerWindowFlutterApi, icefelix_window_manager_window_flutter_api, ICEFELIX_WINDOW_MANAGER, WINDOW_FLUTTER_API, GObject)

/**
 * icefelix_window_manager_window_flutter_api_new:
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Creates a new object to access the WindowFlutterApi API.
 *
 * Returns: a new #IcefelixWindowManagerWindowFlutterApi
 */
IcefelixWindowManagerWindowFlutterApi* icefelix_window_manager_window_flutter_api_new(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * icefelix_window_manager_window_flutter_api_on_snapshot_changed:
 * @api: a #IcefelixWindowManagerWindowFlutterApi.
 * @snapshot: parameter for this method.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 * Called whenever the window snapshot changes. Single notification for all
 * state transitions — Dart side derives WindowEvent from snapshot diff.
 */
void icefelix_window_manager_window_flutter_api_on_snapshot_changed(IcefelixWindowManagerWindowFlutterApi* api, IcefelixWindowManagerWindowSnapshotRaw* snapshot, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * icefelix_window_manager_window_flutter_api_on_snapshot_changed_finish:
 * @api: a #IcefelixWindowManagerWindowFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a icefelix_window_manager_window_flutter_api_on_snapshot_changed() call.
 *
 * Returns: a #IcefelixWindowManagerWindowFlutterApiOnSnapshotChangedResponse or %NULL on error.
 */
IcefelixWindowManagerWindowFlutterApiOnSnapshotChangedResponse* icefelix_window_manager_window_flutter_api_on_snapshot_changed_finish(IcefelixWindowManagerWindowFlutterApi* api, GAsyncResult* result, GError** error);

/**
 * icefelix_window_manager_window_flutter_api_on_displays_changed:
 * @api: a #IcefelixWindowManagerWindowFlutterApi.
 * @displays: parameter for this method.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 * Called when displays are added, removed, or reconfigured.
 */
void icefelix_window_manager_window_flutter_api_on_displays_changed(IcefelixWindowManagerWindowFlutterApi* api, FlValue* displays, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * icefelix_window_manager_window_flutter_api_on_displays_changed_finish:
 * @api: a #IcefelixWindowManagerWindowFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a icefelix_window_manager_window_flutter_api_on_displays_changed() call.
 *
 * Returns: a #IcefelixWindowManagerWindowFlutterApiOnDisplaysChangedResponse or %NULL on error.
 */
IcefelixWindowManagerWindowFlutterApiOnDisplaysChangedResponse* icefelix_window_manager_window_flutter_api_on_displays_changed_finish(IcefelixWindowManagerWindowFlutterApi* api, GAsyncResult* result, GError** error);

/**
 * icefelix_window_manager_window_flutter_api_on_close_request:
 * @api: a #IcefelixWindowManagerWindowFlutterApi.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 * Called when close is requested AND setPreventClose(true) was previously called.
 * Return value: true = allow close (default), false = block.
 *
 * SYNCHRONIZATION CONTRACT FOR NATIVE IMPLEMENTATIONS:
 * - Native side MUST wait for Dart's response before deciding.
 * - Default-allow on timeout: if Dart doesn't respond within 5000ms, treat as `true`
 *   (allow close). Rationale: blocking close indefinitely on a hung Dart isolate
 *   would prevent user from force-quitting the app.
 * - Implementations on macOS/Windows/Linux MUST agree on this timeout to keep
 *   behavior consistent across platforms.
 */
void icefelix_window_manager_window_flutter_api_on_close_request(IcefelixWindowManagerWindowFlutterApi* api, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * icefelix_window_manager_window_flutter_api_on_close_request_finish:
 * @api: a #IcefelixWindowManagerWindowFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a icefelix_window_manager_window_flutter_api_on_close_request() call.
 *
 * Returns: a #IcefelixWindowManagerWindowFlutterApiOnCloseRequestResponse or %NULL on error.
 */
IcefelixWindowManagerWindowFlutterApiOnCloseRequestResponse* icefelix_window_manager_window_flutter_api_on_close_request_finish(IcefelixWindowManagerWindowFlutterApi* api, GAsyncResult* result, GError** error);

G_END_DECLS

#endif  // PIGEON_MESSAGES_G_H_
