// Copyright 2026 icefelix.com. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license
// that can be found in the LICENSE file.
//
// GENERATED CODE — DO NOT EDIT. Edit pigeons/window_api.dart instead.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum WindowStateRaw: Int {
  case normal = 0
  case minimized = 1
  case maximized = 2
  case fullscreen = 3
  case hidden = 4
}

enum TitleBarStyleRaw: Int {
  case normal = 0
  case hidden = 1
  case hiddenInset = 2
}

enum ResizeDirectionRaw: Int {
  case top = 0
  case bottom = 1
  case left = 2
  case right = 3
  case topLeft = 4
  case topRight = 5
  case bottomLeft = 6
  case bottomRight = 7
}

enum DisplayServerRaw: Int {
  case x11 = 0
  case wayland = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct OffsetRaw {
  var dx: Double
  var dy: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OffsetRaw? {
    let dx = pigeonVar_list[0] as! Double
    let dy = pigeonVar_list[1] as! Double

    return OffsetRaw(
      dx: dx,
      dy: dy
    )
  }
  func toList() -> [Any?] {
    return [
      dx,
      dy,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SizeRaw {
  var width: Double
  var height: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SizeRaw? {
    let width = pigeonVar_list[0] as! Double
    let height = pigeonVar_list[1] as! Double

    return SizeRaw(
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RectRaw {
  var x: Double
  var y: Double
  var width: Double
  var height: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RectRaw? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double
    let width = pigeonVar_list[2] as! Double
    let height = pigeonVar_list[3] as! Double

    return RectRaw(
      x: x,
      y: y,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
      width,
      height,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WindowBoundsRaw {
  var position: OffsetRaw? = nil
  var size: SizeRaw


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WindowBoundsRaw? {
    let position: OffsetRaw? = nilOrValue(pigeonVar_list[0])
    let size = pigeonVar_list[1] as! SizeRaw

    return WindowBoundsRaw(
      position: position,
      size: size
    )
  }
  func toList() -> [Any?] {
    return [
      position,
      size,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DisplayRaw {
  var id: String
  var name: String? = nil
  var bounds: RectRaw
  var workArea: RectRaw
  var physicalWidthMm: Double? = nil
  var physicalHeightMm: Double? = nil
  var dpi: Double? = nil
  var scaleFactor: Double
  var isPrimary: Bool
  var refreshRate: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DisplayRaw? {
    let id = pigeonVar_list[0] as! String
    let name: String? = nilOrValue(pigeonVar_list[1])
    let bounds = pigeonVar_list[2] as! RectRaw
    let workArea = pigeonVar_list[3] as! RectRaw
    let physicalWidthMm: Double? = nilOrValue(pigeonVar_list[4])
    let physicalHeightMm: Double? = nilOrValue(pigeonVar_list[5])
    let dpi: Double? = nilOrValue(pigeonVar_list[6])
    let scaleFactor = pigeonVar_list[7] as! Double
    let isPrimary = pigeonVar_list[8] as! Bool
    let refreshRate: Int64? = nilOrValue(pigeonVar_list[9])

    return DisplayRaw(
      id: id,
      name: name,
      bounds: bounds,
      workArea: workArea,
      physicalWidthMm: physicalWidthMm,
      physicalHeightMm: physicalHeightMm,
      dpi: dpi,
      scaleFactor: scaleFactor,
      isPrimary: isPrimary,
      refreshRate: refreshRate
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      bounds,
      workArea,
      physicalWidthMm,
      physicalHeightMm,
      dpi,
      scaleFactor,
      isPrimary,
      refreshRate,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WindowSnapshotRaw {
  var bounds: WindowBoundsRaw
  var state: WindowStateRaw
  var title: String
  var isFocused: Bool
  var alwaysOnTop: Bool
  var skipTaskbar: Bool
  var resizable: Bool
  var movable: Bool
  var minimizable: Bool
  var maximizable: Bool
  var closable: Bool
  var frameless: Bool
  var titleBarStyle: TitleBarStyleRaw
  var opacity: Double
  var backgroundColorArgb: Int64? = nil
  var hasShadow: Bool
  var preventClose: Bool
  var currentDisplay: DisplayRaw


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WindowSnapshotRaw? {
    let bounds = pigeonVar_list[0] as! WindowBoundsRaw
    let state = pigeonVar_list[1] as! WindowStateRaw
    let title = pigeonVar_list[2] as! String
    let isFocused = pigeonVar_list[3] as! Bool
    let alwaysOnTop = pigeonVar_list[4] as! Bool
    let skipTaskbar = pigeonVar_list[5] as! Bool
    let resizable = pigeonVar_list[6] as! Bool
    let movable = pigeonVar_list[7] as! Bool
    let minimizable = pigeonVar_list[8] as! Bool
    let maximizable = pigeonVar_list[9] as! Bool
    let closable = pigeonVar_list[10] as! Bool
    let frameless = pigeonVar_list[11] as! Bool
    let titleBarStyle = pigeonVar_list[12] as! TitleBarStyleRaw
    let opacity = pigeonVar_list[13] as! Double
    let backgroundColorArgb: Int64? = nilOrValue(pigeonVar_list[14])
    let hasShadow = pigeonVar_list[15] as! Bool
    let preventClose = pigeonVar_list[16] as! Bool
    let currentDisplay = pigeonVar_list[17] as! DisplayRaw

    return WindowSnapshotRaw(
      bounds: bounds,
      state: state,
      title: title,
      isFocused: isFocused,
      alwaysOnTop: alwaysOnTop,
      skipTaskbar: skipTaskbar,
      resizable: resizable,
      movable: movable,
      minimizable: minimizable,
      maximizable: maximizable,
      closable: closable,
      frameless: frameless,
      titleBarStyle: titleBarStyle,
      opacity: opacity,
      backgroundColorArgb: backgroundColorArgb,
      hasShadow: hasShadow,
      preventClose: preventClose,
      currentDisplay: currentDisplay
    )
  }
  func toList() -> [Any?] {
    return [
      bounds,
      state,
      title,
      isFocused,
      alwaysOnTop,
      skipTaskbar,
      resizable,
      movable,
      minimizable,
      maximizable,
      closable,
      frameless,
      titleBarStyle,
      opacity,
      backgroundColorArgb,
      hasShadow,
      preventClose,
      currentDisplay,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformInfoRaw {
  var target: String
  var displayServer: DisplayServerRaw? = nil
  var isSandboxed: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformInfoRaw? {
    let target = pigeonVar_list[0] as! String
    let displayServer: DisplayServerRaw? = nilOrValue(pigeonVar_list[1])
    let isSandboxed = pigeonVar_list[2] as! Bool

    return PlatformInfoRaw(
      target: target,
      displayServer: displayServer,
      isSandboxed: isSandboxed
    )
  }
  func toList() -> [Any?] {
    return [
      target,
      displayServer,
      isSandboxed,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WindowStateRaw(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return TitleBarStyleRaw(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ResizeDirectionRaw(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DisplayServerRaw(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      return OffsetRaw.fromList(self.readValue() as! [Any?])
    case 134:
      return SizeRaw.fromList(self.readValue() as! [Any?])
    case 135:
      return RectRaw.fromList(self.readValue() as! [Any?])
    case 136:
      return WindowBoundsRaw.fromList(self.readValue() as! [Any?])
    case 137:
      return DisplayRaw.fromList(self.readValue() as! [Any?])
    case 138:
      return WindowSnapshotRaw.fromList(self.readValue() as! [Any?])
    case 139:
      return PlatformInfoRaw.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? WindowStateRaw {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? TitleBarStyleRaw {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? ResizeDirectionRaw {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? DisplayServerRaw {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? OffsetRaw {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? SizeRaw {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? RectRaw {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? WindowBoundsRaw {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? DisplayRaw {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? WindowSnapshotRaw {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformInfoRaw {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WindowHostApi {
  func ensureInitialized() throws -> WindowSnapshotRaw
  func getPlatformInfo() throws -> PlatformInfoRaw
  func getBounds() throws -> WindowBoundsRaw
  /// Set window bounds. Coordinate system depends on [displayId]:
  /// - If [displayId] is null: bounds.position is in GLOBAL virtual desktop coords.
  /// - If [displayId] is provided: bounds.position is RELATIVE to that display's origin.
  ///
  /// NOTE: distinct from moveToDisplay():
  /// - setBounds(bounds, displayId) = "set window to specific bounds, optionally on display X"
  /// - moveToDisplay(displayId) = "move window to display X, preserving current relative position"
  /// Use setBounds when you have specific coordinates; use moveToDisplay when you just want to switch monitors.
  func setBounds(bounds: WindowBoundsRaw, displayId: String?) throws
  /// Set the window frame size (titlebar included on platforms that have one).
  /// All size APIs and snapshot.bounds.size share this frame-based coordinate
  /// space. Top-left position is preserved.
  func setSize(size: SizeRaw) throws
  /// Set minimum window frame size, or `null` to clear the constraint.
  /// Coordinate space matches [setSize] — same frame, including titlebar.
  /// Future drag-resize and `setSize` calls clamp against this bound.
  func setMinSize(size: SizeRaw?) throws
  /// Set maximum window frame size, or `null` to clear the constraint.
  /// Coordinate space matches [setSize] — same frame, including titlebar.
  /// `maximize()` (a.k.a. zoom) also respects this bound.
  func setMaxSize(size: SizeRaw?) throws
  func setPosition(position: OffsetRaw) throws
  func center() throws
  /// Move window to [displayId], **preserving relative position when possible**.
  /// If the preserved position doesn't fit on the new display, centers instead.
  /// Distinct from setBounds(bounds, displayId) — see setBounds for explicit positioning.
  func moveToDisplay(displayId: String) throws
  func minimize() throws
  func maximize() throws
  func unmaximize() throws
  func restore() throws
  func hide() throws
  func show() throws
  func fullscreen() throws
  func exitFullscreen() throws
  func focus() throws
  func blur() throws
  func startDrag() throws
  func startResize(direction: ResizeDirectionRaw) throws
  func close() throws
  func destroy() throws
  func setTitle(title: String) throws
  func setAlwaysOnTop(value: Bool) throws
  func setSkipTaskbar(value: Bool) throws
  func setResizable(value: Bool) throws
  func setMovable(value: Bool) throws
  func setMinimizable(value: Bool) throws
  func setMaximizable(value: Bool) throws
  func setClosable(value: Bool) throws
  func setFrameless(value: Bool) throws
  func setTitleBarStyle(style: TitleBarStyleRaw) throws
  func setOpacity(opacity: Double) throws
  func setBackgroundColor(argb: Int64) throws
  func setHasShadow(value: Bool) throws
  func setIcon(filesystemPath: String) throws
  /// Replace the window's visible region with a polygon defined by [points]
  /// (window-relative LOGICAL pixels — same coord space as setSize). Pixels
  /// outside the polygon are not part of the window at the OS level: they
  /// don't paint AND clicks pass through to whatever is behind on the desktop.
  ///
  /// Pass `null` to clear the shape and restore the default rectangular
  /// region.
  ///
  /// Platform behavior:
  /// - Windows: implemented via `CreatePolygonRgn` + `SetWindowRgn`. True
  ///   non-rectangular hit-testing. Frameless windows give the cleanest
  ///   result (no chrome around the shape).
  /// - macOS: best-effort via NSWindow.contentView.layer mask. Hit-testing
  ///   for the title bar / chrome is unaffected — clear the title bar via
  ///   setFrameless(true) for the desired effect.
  /// - Linux: deferred to v0.3.0 (X11 SHAPE extension / Wayland subsurface).
  func setShape(points: [OffsetRaw]?) throws
  func setPreventClose(value: Bool) throws
  func listDisplays() throws -> [DisplayRaw]
  func getCurrentDisplay() throws -> DisplayRaw
  func getPrimaryDisplay() throws -> DisplayRaw
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WindowHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `WindowHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WindowHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let ensureInitializedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.ensureInitialized\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      ensureInitializedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.ensureInitialized()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      ensureInitializedChannel.setMessageHandler(nil)
    }
    let getPlatformInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.getPlatformInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPlatformInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPlatformInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPlatformInfoChannel.setMessageHandler(nil)
    }
    let getBoundsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.getBounds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBoundsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getBounds()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getBoundsChannel.setMessageHandler(nil)
    }
    /// Set window bounds. Coordinate system depends on [displayId]:
    /// - If [displayId] is null: bounds.position is in GLOBAL virtual desktop coords.
    /// - If [displayId] is provided: bounds.position is RELATIVE to that display's origin.
    ///
    /// NOTE: distinct from moveToDisplay():
    /// - setBounds(bounds, displayId) = "set window to specific bounds, optionally on display X"
    /// - moveToDisplay(displayId) = "move window to display X, preserving current relative position"
    /// Use setBounds when you have specific coordinates; use moveToDisplay when you just want to switch monitors.
    let setBoundsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.setBounds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setBoundsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let boundsArg = args[0] as! WindowBoundsRaw
        let displayIdArg: String? = nilOrValue(args[1])
        do {
          try api.setBounds(bounds: boundsArg, displayId: displayIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setBoundsChannel.setMessageHandler(nil)
    }
    /// Set the window frame size (titlebar included on platforms that have one).
    /// All size APIs and snapshot.bounds.size share this frame-based coordinate
    /// space. Top-left position is preserved.
    let setSizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.setSize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSizeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sizeArg = args[0] as! SizeRaw
        do {
          try api.setSize(size: sizeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSizeChannel.setMessageHandler(nil)
    }
    /// Set minimum window frame size, or `null` to clear the constraint.
    /// Coordinate space matches [setSize] — same frame, including titlebar.
    /// Future drag-resize and `setSize` calls clamp against this bound.
    let setMinSizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.setMinSize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMinSizeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sizeArg: SizeRaw? = nilOrValue(args[0])
        do {
          try api.setMinSize(size: sizeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMinSizeChannel.setMessageHandler(nil)
    }
    /// Set maximum window frame size, or `null` to clear the constraint.
    /// Coordinate space matches [setSize] — same frame, including titlebar.
    /// `maximize()` (a.k.a. zoom) also respects this bound.
    let setMaxSizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.setMaxSize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMaxSizeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sizeArg: SizeRaw? = nilOrValue(args[0])
        do {
          try api.setMaxSize(size: sizeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMaxSizeChannel.setMessageHandler(nil)
    }
    let setPositionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.setPosition\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPositionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let positionArg = args[0] as! OffsetRaw
        do {
          try api.setPosition(position: positionArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPositionChannel.setMessageHandler(nil)
    }
    let centerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.center\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      centerChannel.setMessageHandler { _, reply in
        do {
          try api.center()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      centerChannel.setMessageHandler(nil)
    }
    /// Move window to [displayId], **preserving relative position when possible**.
    /// If the preserved position doesn't fit on the new display, centers instead.
    /// Distinct from setBounds(bounds, displayId) — see setBounds for explicit positioning.
    let moveToDisplayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.moveToDisplay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      moveToDisplayChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let displayIdArg = args[0] as! String
        do {
          try api.moveToDisplay(displayId: displayIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      moveToDisplayChannel.setMessageHandler(nil)
    }
    let minimizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.minimize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      minimizeChannel.setMessageHandler { _, reply in
        do {
          try api.minimize()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      minimizeChannel.setMessageHandler(nil)
    }
    let maximizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.maximize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      maximizeChannel.setMessageHandler { _, reply in
        do {
          try api.maximize()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      maximizeChannel.setMessageHandler(nil)
    }
    let unmaximizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.unmaximize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unmaximizeChannel.setMessageHandler { _, reply in
        do {
          try api.unmaximize()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      unmaximizeChannel.setMessageHandler(nil)
    }
    let restoreChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.restore\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      restoreChannel.setMessageHandler { _, reply in
        do {
          try api.restore()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      restoreChannel.setMessageHandler(nil)
    }
    let hideChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.hide\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hideChannel.setMessageHandler { _, reply in
        do {
          try api.hide()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      hideChannel.setMessageHandler(nil)
    }
    let showChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.show\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showChannel.setMessageHandler { _, reply in
        do {
          try api.show()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showChannel.setMessageHandler(nil)
    }
    let fullscreenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.fullscreen\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fullscreenChannel.setMessageHandler { _, reply in
        do {
          try api.fullscreen()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      fullscreenChannel.setMessageHandler(nil)
    }
    let exitFullscreenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.exitFullscreen\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      exitFullscreenChannel.setMessageHandler { _, reply in
        do {
          try api.exitFullscreen()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      exitFullscreenChannel.setMessageHandler(nil)
    }
    let focusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.focus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      focusChannel.setMessageHandler { _, reply in
        do {
          try api.focus()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      focusChannel.setMessageHandler(nil)
    }
    let blurChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.blur\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      blurChannel.setMessageHandler { _, reply in
        do {
          try api.blur()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      blurChannel.setMessageHandler(nil)
    }
    let startDragChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.startDrag\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startDragChannel.setMessageHandler { _, reply in
        do {
          try api.startDrag()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startDragChannel.setMessageHandler(nil)
    }
    let startResizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.startResize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startResizeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let directionArg = args[0] as! ResizeDirectionRaw
        do {
          try api.startResize(direction: directionArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startResizeChannel.setMessageHandler(nil)
    }
    let closeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.close\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeChannel.setMessageHandler { _, reply in
        do {
          try api.close()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeChannel.setMessageHandler(nil)
    }
    let destroyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.destroy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      destroyChannel.setMessageHandler { _, reply in
        do {
          try api.destroy()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      destroyChannel.setMessageHandler(nil)
    }
    let setTitleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.setTitle\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setTitleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let titleArg = args[0] as! String
        do {
          try api.setTitle(title: titleArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setTitleChannel.setMessageHandler(nil)
    }
    let setAlwaysOnTopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.setAlwaysOnTop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAlwaysOnTopChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg = args[0] as! Bool
        do {
          try api.setAlwaysOnTop(value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setAlwaysOnTopChannel.setMessageHandler(nil)
    }
    let setSkipTaskbarChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.setSkipTaskbar\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSkipTaskbarChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg = args[0] as! Bool
        do {
          try api.setSkipTaskbar(value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSkipTaskbarChannel.setMessageHandler(nil)
    }
    let setResizableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.setResizable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setResizableChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg = args[0] as! Bool
        do {
          try api.setResizable(value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setResizableChannel.setMessageHandler(nil)
    }
    let setMovableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.setMovable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMovableChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg = args[0] as! Bool
        do {
          try api.setMovable(value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMovableChannel.setMessageHandler(nil)
    }
    let setMinimizableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.setMinimizable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMinimizableChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg = args[0] as! Bool
        do {
          try api.setMinimizable(value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMinimizableChannel.setMessageHandler(nil)
    }
    let setMaximizableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.setMaximizable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMaximizableChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg = args[0] as! Bool
        do {
          try api.setMaximizable(value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMaximizableChannel.setMessageHandler(nil)
    }
    let setClosableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.setClosable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setClosableChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg = args[0] as! Bool
        do {
          try api.setClosable(value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setClosableChannel.setMessageHandler(nil)
    }
    let setFramelessChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.setFrameless\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setFramelessChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg = args[0] as! Bool
        do {
          try api.setFrameless(value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setFramelessChannel.setMessageHandler(nil)
    }
    let setTitleBarStyleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.setTitleBarStyle\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setTitleBarStyleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let styleArg = args[0] as! TitleBarStyleRaw
        do {
          try api.setTitleBarStyle(style: styleArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setTitleBarStyleChannel.setMessageHandler(nil)
    }
    let setOpacityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.setOpacity\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setOpacityChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let opacityArg = args[0] as! Double
        do {
          try api.setOpacity(opacity: opacityArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setOpacityChannel.setMessageHandler(nil)
    }
    let setBackgroundColorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.setBackgroundColor\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setBackgroundColorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let argbArg = args[0] as! Int64
        do {
          try api.setBackgroundColor(argb: argbArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setBackgroundColorChannel.setMessageHandler(nil)
    }
    let setHasShadowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.setHasShadow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setHasShadowChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg = args[0] as! Bool
        do {
          try api.setHasShadow(value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setHasShadowChannel.setMessageHandler(nil)
    }
    let setIconChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.setIcon\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setIconChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filesystemPathArg = args[0] as! String
        do {
          try api.setIcon(filesystemPath: filesystemPathArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setIconChannel.setMessageHandler(nil)
    }
    /// Replace the window's visible region with a polygon defined by [points]
    /// (window-relative LOGICAL pixels — same coord space as setSize). Pixels
    /// outside the polygon are not part of the window at the OS level: they
    /// don't paint AND clicks pass through to whatever is behind on the desktop.
    ///
    /// Pass `null` to clear the shape and restore the default rectangular
    /// region.
    ///
    /// Platform behavior:
    /// - Windows: implemented via `CreatePolygonRgn` + `SetWindowRgn`. True
    ///   non-rectangular hit-testing. Frameless windows give the cleanest
    ///   result (no chrome around the shape).
    /// - macOS: best-effort via NSWindow.contentView.layer mask. Hit-testing
    ///   for the title bar / chrome is unaffected — clear the title bar via
    ///   setFrameless(true) for the desired effect.
    /// - Linux: deferred to v0.3.0 (X11 SHAPE extension / Wayland subsurface).
    let setShapeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.setShape\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setShapeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pointsArg: [OffsetRaw]? = nilOrValue(args[0])
        do {
          try api.setShape(points: pointsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setShapeChannel.setMessageHandler(nil)
    }
    let setPreventCloseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.setPreventClose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPreventCloseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg = args[0] as! Bool
        do {
          try api.setPreventClose(value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPreventCloseChannel.setMessageHandler(nil)
    }
    let listDisplaysChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.listDisplays\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listDisplaysChannel.setMessageHandler { _, reply in
        do {
          let result = try api.listDisplays()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      listDisplaysChannel.setMessageHandler(nil)
    }
    let getCurrentDisplayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.getCurrentDisplay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCurrentDisplayChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCurrentDisplay()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCurrentDisplayChannel.setMessageHandler(nil)
    }
    let getPrimaryDisplayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowHostApi.getPrimaryDisplay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPrimaryDisplayChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPrimaryDisplay()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPrimaryDisplayChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol WindowFlutterApiProtocol {
  /// Called whenever the window snapshot changes. Single notification for all
  /// state transitions — Dart side derives WindowEvent from snapshot diff.
  func onSnapshotChanged(snapshot snapshotArg: WindowSnapshotRaw, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when displays are added, removed, or reconfigured.
  func onDisplaysChanged(displays displaysArg: [DisplayRaw], completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when close is requested AND setPreventClose(true) was previously called.
  /// Return value: true = allow close (default), false = block.
  ///
  /// SYNCHRONIZATION CONTRACT FOR NATIVE IMPLEMENTATIONS:
  /// - Native side MUST wait for Dart's response before deciding.
  /// - Default-allow on timeout: if Dart doesn't respond within 5000ms, treat as `true`
  ///   (allow close). Rationale: blocking close indefinitely on a hung Dart isolate
  ///   would prevent user from force-quitting the app.
  /// - Implementations on macOS/Windows/Linux MUST agree on this timeout to keep
  ///   behavior consistent across platforms.
  func onCloseRequest(completion: @escaping (Result<Bool, PigeonError>) -> Void)
}
class WindowFlutterApi: WindowFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  /// Called whenever the window snapshot changes. Single notification for all
  /// state transitions — Dart side derives WindowEvent from snapshot diff.
  func onSnapshotChanged(snapshot snapshotArg: WindowSnapshotRaw, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowFlutterApi.onSnapshotChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([snapshotArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Called when displays are added, removed, or reconfigured.
  func onDisplaysChanged(displays displaysArg: [DisplayRaw], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowFlutterApi.onDisplaysChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([displaysArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Called when close is requested AND setPreventClose(true) was previously called.
  /// Return value: true = allow close (default), false = block.
  ///
  /// SYNCHRONIZATION CONTRACT FOR NATIVE IMPLEMENTATIONS:
  /// - Native side MUST wait for Dart's response before deciding.
  /// - Default-allow on timeout: if Dart doesn't respond within 5000ms, treat as `true`
  ///   (allow close). Rationale: blocking close indefinitely on a hung Dart isolate
  ///   would prevent user from force-quitting the app.
  /// - Implementations on macOS/Windows/Linux MUST agree on this timeout to keep
  ///   behavior consistent across platforms.
  func onCloseRequest(completion: @escaping (Result<Bool, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.icefelix_window_manager_platform_interface.WindowFlutterApi.onCloseRequest\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! Bool
        completion(.success(result))
      }
    }
  }
}
